Team Rocket Robotics: common.c File Reference
common.c File Reference
Common mathematics routines.
#include <math.h>
#include "common.h"
Functions
float toRadian (float n)
Convert degree to radian.
float toDegree (float n)
Convert radian to degree.
float abs (float n)
get absolute value
Detailed Description
Common mathematics routines.
These maths routines are not included in math.h.
Author
Fufu Fang (wrote the whole thing)
Definition in file common.c.
Function Documentation
float abs (float n)
get absolute value
Parameters
[in] n a number
Definition at line 21 of file common.c.
{
    if (n < 0) {
        n = -n;
    }
    return n;
}
float toDegree (float n)
Convert radian to degree.
Definition at line 16 of file common.c.
Referenced by adv_move(), adv_move_pid(), coordinate_update(), dbg_print_coordinate(), and encoder_submit().
{
    return n / M_PI * 180;
}
float toRadian (float n)
Convert degree to radian.
Definition at line 11 of file common.c.
Referenced by mouse_callback().
{
    return n / 180 * M_PI;
}