Team Rocket Robotics: coordinate.c File Reference
coordinate.c File Reference
Coordinate record module.
#include <math.h>
#include "debug.h"
#include "lcd.h"
#include "motor.h"
#include "common.h"
#include "advanced_movement.h"
#include "coordinate.h"
Macros
#define PID_FACTOR 11.111
#define PID_CAP
Functions
void coordinate_angle_set (int n)
set the target angle for the pid line following algorithm
void coordinate_clear ()
Clear coordinate record.
void coordinate_update (Polar update)
Update global Coordinate record.
Coordinate coordinate_read ()
read global coordinate record
void distance_clear ()
clear distance record.
float distance_read ()
read total distance travelled
Variables
static Coordinate g_coord = {0, 0, 0}
static Coordinate g_diff = {0, 0, 0}
static float g_distance = 0
static int g_target_angle = 0
Detailed Description
Coordinate record module.
Author
Fufu Fang (wrote the whole thing)
Note
PID_FACTOR scales the pid value, so it is between (-2000 .. 0 .. 2000)
5.555 -> (-180 .. 0 ..180)
11.111 -> (-90 .. 0 .. 90)
22.222 -> (-45 .. 0 .. 45)
Definition in file coordinate.c.
Macro Definition Documentation
#define PID_CAP
Definition at line 22 of file coordinate.c.
#define PID_FACTOR 11.111
Definition at line 20 of file coordinate.c.
Referenced by coordinate_update().
Function Documentation
void coordinate_angle_set (int n)
set the target angle for the pid line following algorithm
Parameters
[in] n the target angle (between 0 - 360 degrees)
Definition at line 29 of file coordinate.c.
References g_target_angle.
Referenced by adv_move_pid_polar().
{
    /* defensive programming, avoid crazy input */
    if (n < 0 || n > 360) {
        n = 0;
    }
    g_target_angle = n - 180;
}
void coordinate_clear ()
Clear coordinate record.
Definition at line 38 of file coordinate.c.
References Coordinate::t, Coordinate::x, and Coordinate::y.
{
    g_coord.x = 0;
    g_coord.y = 0;
    g_coord.t = 0;
}
Coordinate coordinate_read ()
read global coordinate record
the global coordinate record contains the coordinate the robot is on. Both x and y are in unit of cm, whereas the angle is in radian. It is normalised between 0 and 2pi.
Definition at line 88 of file coordinate.c.
References g_coord.
Referenced by adv_move(), adv_move_pid(), and bullet_point_3().
{
    return g_coord;
}
void coordinate_update (Polar update)
Update global Coordinate record.
Apply transformation to the coordinate update, and add the changes to the global record.
Parameters
update the change in coordinate in local frame of reference
Definition at line 45 of file coordinate.c.
References adv_angle_update(), dbg_print_coordinate(), dbg_printf(), g_distance, g_target_angle, lcd_print_coordinate(), motor_angle_sync(), PID_FACTOR, Polar::r, Coordinate::t, Polar::t, toDegree(), Coordinate::x, and Coordinate::y.
Referenced by encoder_submit(), and mouse_callback().
{
    g_diff.t = update.t;
    g_coord.t += g_diff.t;
    /* Code for normalising angle record
     * between 0 to 2pi */
    if (g_coord.t < 0) {
        g_coord.t += 2*M_PI;
    }
    if (g_coord.t > (2*M_PI)) {
        g_coord.t -= 2*M_PI;
    }
    g_distance += update.r;
    g_diff.x = update.r * sin(g_coord.t);
    g_diff.y = update.r * cos(g_coord.t);
    g_coord.x += g_diff.x;
    g_coord.y += g_diff.y;
    int degree = (int)toDegree(g_coord.t);
    motor_angle_sync(degree);
    int pid_angle = (degree - 180 - g_target_angle) * PID_FACTOR;
    /* capping normalised_angle */
    #ifdef PID_CAP
    if (pid_angle > 2000) {
        pid_angle = 2000;
    } else if (pid_angle < -2000) {
        pid_angle = -2000;
    }
    #endif
    adv_angle_update(pid_angle);
    lcd_print_coordinate(g_coord);
    #ifdef COORD_DBG
        dbg_printf("Coordinate.c:  ");
        dbg_print_coordinate(g_coord);
    #endif
}
void distance_clear ()
clear distance record.
Definition at line 93 of file coordinate.c.
References g_distance.
Referenced by adv_motors_rpm(), adv_move_pid_polar(), and adv_travel().
{
    g_distance = 0;
}
float distance_read ()
read total distance travelled
Definition at line 98 of file coordinate.c.
References dbg_printf(), and g_distance.
Referenced by adv_motors_rpm(), adv_move_pid_polar(), and adv_travel().
{
    #ifdef DISTANCE_DBG
        dbg_printf("Coordinate.c: Distance: %f\r\n", g_distance);
    #endif
    return g_distance;
}
Variable Documentation
Coordinate g_coord = {0, 0, 0} static
Definition at line 24 of file coordinate.c.
Referenced by coordinate_read().
Coordinate g_diff = {0, 0, 0} static
Definition at line 25 of file coordinate.c.
float g_distance = 0 static
Definition at line 26 of file coordinate.c.
Referenced by coordinate_update(), distance_clear(), and distance_read().
int g_target_angle = 0 static
Definition at line 27 of file coordinate.c.
Referenced by coordinate_angle_set(), and coordinate_update().