Team Rocket Robotics: debug.h File Reference
debug.h File Reference
debug framework enhancer header
#include <debug_frmwrk.h>
#include "mouse.h"
Macros
#define dbg_getchar() _DG
Macro Functions.
Functions
int dbg_printf (const char *format,...)
printf function for the debugging console
void dbg_print_coordinate (Coordinate record)
print a coordinate record to the console
Detailed Description
debug framework enhancer header
Author
Fufu Fang (wrote the whole thing)
Definition in file debug.h.
Macro Definition Documentation
#define dbg_getchar () _DG
Macro Functions.
Definition at line 16 of file debug.h.
Function Documentation
void dbg_print_coordinate (Coordinate record)
print a coordinate record to the console
Parameters
[in] record the record to be printed
Definition at line 28 of file debug.c.
References dbg_printf(), Coordinate::t, toDegree(), Coordinate::x, and Coordinate::y.
Referenced by coordinate_update().
{
    dbg_printf("x: %f\ty: %f\tt: %f\r\n", record.x, record.y, toDegree(record.t));
}
int dbg_printf (const char * format, ...)
printf function for the debugging console
Precondition
you need to call debug_frmwrk_init() first!
Parameters
*format the formatting string
... any variable you want to include in the formatted string
Returns
the number of characters printed
Definition at line 16 of file debug.c.
Referenced by adv_motors_rpm(), adv_move(), adv_print_rmp(), coordinate_update(), dbg_print_coordinate(), delay_music(), delay_start(), distance_read(), EINT3_IRQHandler(), encoder_clear(), encoder_rpm_calculate(), encoder_rpm_clear(), encoder_submit(), encoder_update(), init(), internal_motor_rotate(), motor_angle(), motor_angle_sync(), motor_rot_abs(), motor_rot_rel(), mouse_attach(), mouse_detach(), mouse_setup(), pid_calc(), pid_clear(), pid_exit_check(), pid_line_detect(), pid_motor_set(), pid_over_line(), pid_read_sensors(), pid_run(), pid_set(), play_music(), read_battery(), and read_trimpot().
{
    va_list arg;
    char processed[256];
    va_start(arg, format);
    int n = vsnprintf(processed, 256, format, arg);
    va_end(arg);
    processed[255] = '\0';
    _DBG(processed);
    return n;
}