Team Rocket Robotics: delay.h File Reference
delay.h File Reference
Timer functions for causing delay (header)
Functions
void delay_start (int delay_length)
Delay function.
void delay_music (int tempo, int beats_per_bar, int num_bars)
Music delay function.
Detailed Description
Timer functions for causing delay (header)
Author
Sam Gamble
Fufu Fang (tidying up)
Definition in file delay.h.
Function Documentation
void delay_music (int tempo, int beats_per_bar, int num_bars)
Music delay function.
This function is used for sending music strings one after the other, a delay is required to stop the 2nd string overwriting the first.
Definition at line 61 of file delay.c.
References dbg_printf(), and delay_start().
{
    dbg_printf("Calculating time delay --  Tempo: %d  BPB: %d  num bars: %d   \n\r", tempo, beats_per_bar, num_bars);
    float music_duration = ((60 / (float) tempo) * (float) beats_per_bar * (float) num_bars) * 1000.0;
    int delay_length = (int) music_duration;
    dbg_printf("Result (Milliseconds):  %d   \n\r", delay_length);
    delay_start(delay_length);
}
void delay_start (int delay_length)
Delay function.
cause the C function to delay certain amount of milliseconds, to be used instead of waiting loops.
Parameters
delay_length The length of delay in milliseconds
crash avoidance – if you ask the timer to wait for 0, it will crash. (Added by Fufu)
Definition at line 39 of file delay.c.
References dbg_printf(), delay_init(), LED_0, led_off(), and led_on().
Referenced by bullet_point_3(), delay_music(), docking_station_1(), docking_station_2(), internal_motor_rotate(), nav_follow_wall(), and nav_search_line().
{
    if (delay_length == 0){
        dbg_printf("WARNING:You have just asked the timer to wait for 0 miliseconds.\r\n");
        return;
    }
    led_on(LED_0);
    delay_init(delay_length);
    /* Start timer */
    TIM_Cmd(LPC_TIM0, ENABLE);
    while (!TIM_GetIntStatus(LPC_TIM0, TIM_MR0_INT))
        ;
    TIM_ClearIntPending(LPC_TIM0, 0);
    TIM_DeInit(LPC_TIM0);
    led_off(LED_0);
}