Team Rocket Robotics: gpio.h File Reference
gpio.h File Reference
Collision sensor controller header.
Functions
void gpio_init ()
Initialise collision sensor.
int gpio_collision_read ()
Read collision sensor data.
int gpio_button_read ()
Read button.
void EINT3_IRQHandler ()
Interrupt Service Routine for GPIO ports.
void gpio_int_enable ()
Enable GPIO interrupt.
void gpio_int_disable ()
Disable GPIO interrupt.
void gpio_button_wait ()
Wait for GPIO button click.
void gpio_collision_wait ()
Wait for collision.
Detailed Description
Collision sensor controller header.
Note
pin.h is in the source file, because its content does not need to be exposed to the public.
Author
Fufu Fang (wrote the initialisation and polling code, general clean up)
Nathan Bartram (wrote the interrupt code)
Definition in file gpio.h.
Function Documentation
void EINT3_IRQHandler ()
Interrupt Service Routine for GPIO ports.
Only one interrupt service routine is available for all GPIO pins.
Definition at line 65 of file gpio.c.
References BUTTON_DETECT_PIN_NUM, BUTTON_PIN, BUTTON_PORT, COLLISION_SENSOR_PIN, COLLISION_SENSOR_PIN_NUM, COLLISION_SENSOR_PORT, dbg_printf(), ENCODER_PORT, encoder_update(), LEFT_ENCODER, LEFT_PIN, LEFT_PIN_NUM, RIGHT_ENCODER, RIGHT_PIN, and RIGHT_PIN_NUM.
{
    if (GPIO_GetIntStatus(ENCODER_PORT, RIGHT_PIN_NUM, 0)) {
        #ifdef GPIO_DBG
        dbg_printf("Right Wheel Encoder!\n\r");
        #endif
        #ifdef WHEEL_ENCODER
        encoder_update(RIGHT_ENCODER);
        #endif
        GPIO_ClearInt(ENCODER_PORT, RIGHT_PIN);
    }
    if (GPIO_GetIntStatus(ENCODER_PORT, LEFT_PIN_NUM, 0)) {
        #ifdef GPIO_DBG
        dbg_printf("Left Wheel Encoder!\n\r");
        #endif
        #ifdef WHEEL_ENCODER
        encoder_update(LEFT_ENCODER);
        #endif
        GPIO_ClearInt(ENCODER_PORT, LEFT_PIN);
    }
    if (GPIO_GetIntStatus(ENCODER_PORT, RIGHT_PIN_NUM, 1)) {
        #ifdef GPIO_DBG
        dbg_printf("Right Wheel Encoder!\n\r");
        #endif
        #ifdef WHEEL_ENCODER
        encoder_update(RIGHT_ENCODER);
        #endif
        GPIO_ClearInt(ENCODER_PORT, RIGHT_PIN);
    }
    if (GPIO_GetIntStatus(ENCODER_PORT, LEFT_PIN_NUM, 1)) {
        #ifdef GPIO_DBG
        dbg_printf("Left Wheel Encoder!\n\r");
        #endif
        #ifdef WHEEL_ENCODER
        encoder_update(LEFT_ENCODER);
        #endif
        GPIO_ClearInt(ENCODER_PORT, LEFT_PIN);
    }
    if (GPIO_GetIntStatus(BUTTON_PORT, BUTTON_DETECT_PIN_NUM, 0)) {
        #ifdef GPIO_DBG
        dbg_printf("Button pressed!\n\r");
        #endif
        GPIO_ClearInt(BUTTON_PORT, BUTTON_PIN);
    }
    if (GPIO_GetIntStatus(COLLISION_SENSOR_PORT, COLLISION_SENSOR_PIN_NUM, 1)) {
        #ifdef GPIO_DBG
        dbg_printf("Collision warning!\n\r");
        #endif
        GPIO_ClearInt(COLLISION_SENSOR_PORT, COLLISION_SENSOR_PIN);
    }
    #ifdef GPIO_DBG
        dbg_printf("GPIO Port values: %d\r\n", GPIO_ReadValue(0));
    #endif
}
int gpio_button_read ()
Read button.
Returns
0, if button is not pressed; 1, if button is pressed
Definition at line 53 of file gpio.c.
References BUTTON_PIN, and BUTTON_PORT.
Referenced by gpio_button_wait(), and main_hold().
{
    if (BUTTON_PIN & GPIO_ReadValue(BUTTON_PORT)) {
        return 0;
    } else {
        return 1;
    }
}
void gpio_button_wait ()
Wait for GPIO button click.
Do nothing until the GPIO button is clicked.
Definition at line 157 of file gpio.c.
References gpio_button_read(), LED_ALL, led_off(), and led_on().
Referenced by bullet_point_4(), and init().
{
    while (gpio_button_read()==0) {
        led_on(LED_ALL);
    }
    led_off(LED_ALL);
}
int gpio_collision_read ()
Read collision sensor data.
Returns
0, if no object is detected; 1, if collision is imminent.
Definition at line 44 of file gpio.c.
References COLLISION_SENSOR_PIN, and COLLISION_SENSOR_PORT.
Referenced by gpio_collision_wait(), and nav_follow_wall().
{
    if (COLLISION_SENSOR_PIN & GPIO_ReadValue(COLLISION_SENSOR_PORT)) {
        return 0;
    } else {
        return 1;
    }
}
void gpio_collision_wait ()
Wait for collision.
Do nothing until a collision is detected.
Definition at line 165 of file gpio.c.
References gpio_collision_read(), LED_ALL, led_off(), and led_on().
{
    while (gpio_collision_read()==0) {
        led_on(LED_ALL);
    }
    led_off(LED_ALL);
}
void gpio_init ()
Initialise collision sensor.
Note
Please configure the pin and port number accordingly.
Definition at line 36 of file gpio.c.
References BUTTON_PIN, BUTTON_PORT, COLLISION_SENSOR_PIN, COLLISION_SENSOR_PORT, ENCODER_PORT, LEFT_PIN, and RIGHT_PIN.
Referenced by init().
{
    GPIO_SetDir(ENCODER_PORT, LEFT_PIN, 0);
    GPIO_SetDir(ENCODER_PORT, RIGHT_PIN, 0);
    GPIO_SetDir(COLLISION_SENSOR_PORT, COLLISION_SENSOR_PIN, 0);
    GPIO_SetDir(BUTTON_PORT, BUTTON_PIN, 0);
}
void gpio_int_disable ()
Disable GPIO interrupt.
Definition at line 152 of file gpio.c.
{
    NVIC_DisableIRQ(EINT3_IRQn);
}
void gpio_int_enable ()
Enable GPIO interrupt.
Note
There are four interrupt can be set. They are:
Port 0 Rising edge
Port 0 Lowering edge
Port 2 Rising edge
Port 2 Lowering edge
Definition at line 137 of file gpio.c.
References BUTTON_PIN, BUTTON_PORT, COLLISION_SENSOR_PIN, COLLISION_SENSOR_PORT, ENCODER_PINS, and ENCODER_PORT.
Referenced by init().
{
    /* Wheel encoders are triggered at rising edge */
    GPIO_IntCmd(ENCODER_PORT, ENCODER_PINS, 0);
    /* Button interrupt is triggered at rising edge */
    GPIO_IntCmd(BUTTON_PORT, BUTTON_PIN, 0);
    /* Collision sensor interrupt is triggered at falling edge */
    GPIO_IntCmd(COLLISION_SENSOR_PORT, COLLISION_SENSOR_PIN|ENCODER_PINS, 1);
    /* Enable interrupt */
    NVIC_EnableIRQ(EINT3_IRQn);
}