Team Rocket Robotics: lcd.h File Reference
lcd.h File Reference
LCD controller header.
#include "coordinate.h"
Functions
int lcd_printf (const char *format,...)
printf function for the lcd
void lcd_init ()
initialise LCD screen
void lcd_clear ()
clear LCD screen
void lcd_goto (short x, short y)
move LCD cursor
void lcd_next_line ()
move to the next line
void lcd_print_coordinate (Coordinate record)
print a coordinate record on LCD
Detailed Description
LCD controller header.
Precondition
You should call lcd_clear() first before running any other function. This reset the location of the LCD cursor.
Author
Fufu Fang (wrote the whole thing)
Definition in file lcd.h.
Function Documentation
void lcd_clear ()
clear LCD screen
clear LCD screen, the cursor is moved to 0, 0.
Definition at line 60 of file lcd.c.
References lcd_goto(), and lcd_printf().
Referenced by lcd_print_coordinate().
{
    lcd_goto(0, 0);
    lcd_printf("          ");
    lcd_printf("          ");
    lcd_goto(0, 0);
}
void lcd_goto (short x, short y)
move LCD cursor
move LCD cursor to the coordinate x,y.
Parameters
x the column
y the row
Definition at line 68 of file lcd.c.
References LCD_GOTO_XY, lcd_x, lcd_y, and uart_send_blk().
Referenced by lcd_clear(), and lcd_next_line().
{
    uint8_t cmd[] = { LCD_GOTO_XY, x, y };
    uart_send_blk(cmd, 3);
    lcd_x = x;
    lcd_y = y;
}
void lcd_init ()
initialise LCD screen
Clear LCD screen using a single UART command, then set the internal x,y counters to 0.
Definition at line 53 of file lcd.c.
References CLEAR_LCD, lcd_x, lcd_y, and uart_send_byte().
{
    lcd_x = 0;
    lcd_y = 0;
    uart_send_byte(CLEAR_LCD);
}
void lcd_next_line ()
move to the next line
move the cursor to the beginning of the next line. If the cursor is at * the first line, it will move to the second line. If the cursor is at the second line, it will move to the first line.
Definition at line 76 of file lcd.c.
References lcd_goto(), lcd_x, and lcd_y.
Referenced by lcd_print_coordinate(), and lcd_printf().
{
    if (lcd_y == 0) {
        lcd_goto(0, 1);
        lcd_x = 0;
        lcd_y = 1;
    } else {
        lcd_goto(0, 0);
        lcd_x = 0;
        lcd_y = 0;
    }
}
void lcd_print_coordinate (Coordinate record)
print a coordinate record on LCD
Parameters
[in] record the record to be printed
Definition at line 89 of file lcd.c.
References lcd_clear(), lcd_next_line(), lcd_printf(), Coordinate::x, and Coordinate::y.
Referenced by bullet_point_3(), and coordinate_update().
{
    lcd_clear();
    lcd_printf("x:%d", (int)record.x);
    lcd_next_line();
    lcd_printf("y:%d", (int)record.y);
}
int lcd_printf (const char * format, ...)
printf function for the lcd
Warning
Each line on the LCD only allows 8 characters. If you go over the 8 characters limit during a function call, characters over the limit will be truncated.
If the function detects that you have gone over the 8-character limit after a function call. It will automatically move the cursor to the next line.
Parameters
*format the formatting string
... any variable you want to include in the formatted string
Returns
the number of characters printed
Definition at line 23 of file lcd.c.
References lcd_next_line(), lcd_x, PRINT, temp, and uart_send_blk().
Referenced by lcd_clear(), and lcd_print_coordinate().
{
    va_list arg;
    char temp[12];
    temp[2] = '\0';
    strcat(temp, format);
    char *processed = &temp[2];
    va_start(arg, format);
    int n = vsnprintf(processed, 9, format, arg);
    va_end(arg);
    temp[0] = PRINT;
    temp[1] = strlen(temp) - 2;
    temp[11] = '\0';
    uint8_t *data = (uint8_t *) temp;
    uart_send_blk(data, strlen(temp));
    lcd_x += n;
    if (lcd_x > 7) {
        lcd_next_line();
    }
    return n;
}