Team Rocket Robotics: led.c File Reference
led.c File Reference
LED controller.
#include <lpc17xx_gpio.h>
#include "led.h"
Functions
void led_init ()
LED initialisation.
void led_set (int led)
Set the status of specified LED.
void led_on (int led)
Turn on certain LED.
void led_off (int led)
Turn off certain LED.
Detailed Description
LED controller.
Author
Fufu Fang (wrote the whole thing)
Definition in file led.c.
Function Documentation
void led_init ()
LED initialisation.
Definition at line 9 of file led.c.
References LED_ALL.
{
    GPIO_SetDir(1, LED_ALL, 1);
}
void led_off (int led)
Turn off certain LED.
Definition at line 25 of file led.c.
Referenced by delay_start(), gpio_button_wait(), gpio_collision_wait(), init(), TIMER2_IRQHandler(), and TIMER3_IRQHandler().
{
    GPIO_ClearValue(1, led);
}
void led_on (int led)
Turn on certain LED.
Definition at line 20 of file led.c.
Referenced by delay_start(), gpio_button_wait(), gpio_collision_wait(), TIMER2_IRQHandler(), and TIMER3_IRQHandler().
{
    GPIO_SetValue(1, led);
}
void led_set (int led)
Set the status of specified LED.
Definition at line 14 of file led.c.
References LED_ALL.
{
    GPIO_ClearValue(1, LED_ALL);
    GPIO_SetValue(1, led);
}