Team Rocket Robotics: line_follow.h File Reference
line_follow.h File Reference
Contains line following algorithms headers.
Functions
void nav_follow_line (int speed)
Set the robot to follow a line.
void nav_stop_follow_line ()
Stop the line following algorithm.
Detailed Description
Contains line following algorithms headers.
Author
Oliver Loftus
Definition in file line_follow.h.
Function Documentation
void nav_follow_line (int speed)
Set the robot to follow a line.
Definition at line 14 of file line_follow.c.
References START_PID, and uart_send_blk().
Referenced by pid_set().
{
  uint8_t command[] = { START_PID, speed, 1, 20, 3, 2 };
  uart_send_blk(command, 6);
}
void nav_stop_follow_line ()
Stop the line following algorithm.
Definition at line 20 of file line_follow.c.
References STOP_PID, and uart_send_byte().
Referenced by pid_clear().
{
  uart_send_byte(STOP_PID);
}