Team Rocket Robotics: line_sensors.h File Reference
line_sensors.h File Reference
Header for the line sensor module.
#include <stdint.h>
Functions
void line_read (uint16_t *result)
Reads the calibrated values from line sensors.
void line_read_raw (uint16_t *result)
Read the raw values of line sensors into an array.
void line_calibrate_read (uint16_t *result)
Calibrate and Read.
uint16_t line_read_position ()
Get current estimated line position.
void line_calibration_reset ()
Resets line sensor calibration.
int line_autocalibrate ()
Built-in line sensor auto-calibration.
int line_detect ()
Detect the presence of the line.
Detailed Description
Header for the line sensor module.
Author
Sam Gamble (created the file,)
Fufu Fang (clean up, added function descriptions)
Definition in file line_sensors.h.
Function Documentation
int line_autocalibrate ()
Built-in line sensor auto-calibration.
This function cause the Pololu robot to run through an automatic calibration sequence for IR line sensors. It is described in: http://www.pololu.com/docs/0J21/10.a
How it works:
Rotates right, calibrates sensors
Rotates left, calibrates sensors
Rotates right, calibrates sensors
motors off, Sends confirm byte "c" on completion
For information please search auto_calibrate() in http://www.pololu.com/docs/0J21/10.a
Definition at line 126 of file line_sensors.c.
References AUTOCALIBRATE, uart_recv_blk(), and uart_send_byte().
Referenced by bullet_point_4(), and init().
{
    uint8_t read_buffer;
    uart_send_byte(AUTOCALIBRATE);
    /* The robot will return a single byte, when the calibration is
     * complete */
    if (uart_recv_blk(&read_buffer, 1)) {
        return 1;
    } else {
        return 0;
    }
}
void line_calibrate_read (uint16_t * result)
Calibrate and Read.
Parameters
result An uint16_t array to store the result.
Perform one round of calibration, then perform a calibrated read. This are all done using Pololu's internal routines.
For more information, please search 0xB4 in http://www.pololu.com/docs/0J21/10.a
Definition at line 104 of file line_sensors.c.
References CALIBRATE_AND_READ, uart_recv_blk(), and uart_send_byte().
{
    uint8_t* new_result = (uint8_t*) result;
    uart_send_byte(CALIBRATE_AND_READ);
    uart_recv_blk(new_result, 10);
}
void line_calibration_reset ()
Resets line sensor calibration.
This function sends a command byte to resets the line sensor calibration data stored on Pololu
Definition at line 91 of file line_sensors.c.
References RESET_CALIBRATION, and uart_send_byte().
{
    uart_send_byte(RESET_CALIBRATION);
}
int line_detect ()
Detect the presence of the line.
This function checks if the 3rd line sensor (the central one) is above the black line.
Returns
0 for no line, 1 for line detected
Definition at line 145 of file line_sensors.c.
References line_read().
{
    uint16_t result[5];
    line_read(result);
    if (result[2] <= 900) {
        return 1;
    } else {
        return 0;
    }
}
void line_read (uint16_t * result)
Reads the calibrated values from line sensors.
Parameters
result An uint16_t array to store the result. while 1000 represents black
This function reads the sensor values into an array. The robot only performs a new reading if we are not in PID mode. Otherwise, it sends the most recent result immediately.
Example usage:
unsigned int sensor_values[8];
sensors.read(sensor_values);
Warning
the size of result array must be enough to contain 5 uint16_t values, or 10 uint8_t values.
Returns
The values returned (between 0-1000) are measures of reflectance in arbitary units, with * higher values corresponding to lower reflectance. 0 represents white,
Definition at line 47 of file line_sensors.c.
References READ_CALIBRATED_SENSORS, uart_recv_blk(), and uart_send_byte().
Referenced by line_detect(), and pid_read_sensors().
{
    uint8_t* new_result = (uint8_t*) result;
    uart_send_byte(READ_CALIBRATED_SENSORS);
    uart_recv_blk(new_result, 10);
}
uint16_t line_read_position ()
Get current estimated line position.
Returns
an estimated position of the line;
Reads all five IR sensors using calibrated values and estimates the position of a black line under the robot.
For more information, please search send_line_position() and 0xB6 in http://www.pololu.com/docs/0J21/10.a
Definition at line 72 of file line_sensors.c.
References READ_LINE_POSITION, temp, uart_recv_blk(), and uart_send_byte().
{
    uint16_t result = 0;
    uint8_t* temp = (uint8_t*) &result;
    uart_send_byte(READ_LINE_POSITION);
    uart_recv_blk(temp, 2);
    /* Debug info */
    //dbg_printf("Line Pos recived: %X %X   ",temp[0],temp[1]);
    //dbg_printf("  Convert: %u\r\n",result);
    return result;
}
void line_read_raw (uint16_t * result)
Read the raw values of line sensors into an array.
This function performs the same function as line_read, except it returns the raw readings.
Definition at line 58 of file line_sensors.c.
References READ_RAW_SENSORS, uart_recv_blk(), and uart_send_byte().
{
    uint8_t* new_result = (uint8_t*) result;
    uart_send_byte(READ_RAW_SENSORS);
    uart_recv_blk(new_result, 10);
}