Team Rocket Robotics: line_search.c File Reference
line_search.c File Reference
line-searching algorithm (source)
#include "line_search.h"
#include "motor.h"
#include "delay.h"
#include "pid.h"
#include "rit.h"
#include <lpc17xx_systick.h>
#include <lpc17xx_rit.h>
Macros
#define EDGE_DELAY 4000
#define EDGE_SPEED 20
Functions
void RIT_IRQHandler ()
void nav_search_line ()
Line searching algorithm entry point.
void nav_stop_search_line ()
Stop the line searching algorithm.
Variables
static int lineSearching = 0
Detailed Description
line-searching algorithm (source)
Author
Oliver Loftus
Definition in file line_search.c.
Macro Definition Documentation
#define EDGE_DELAY 4000
Definition at line 17 of file line_search.c.
Referenced by nav_search_line().
#define EDGE_SPEED 20
Definition at line 18 of file line_search.c.
Referenced by nav_search_line().
Function Documentation
void nav_search_line ()
Line searching algorithm entry point.
Definition at line 29 of file line_search.c.
References delay_start(), EDGE_DELAY, EDGE_SPEED, lineSearching, motor_rot_rel(), motors_move(), motors_stop(), pid_line_detect(), and RIT_Start().
{
  RIT_Start(100);
//  int initSpeed = motor_read(MOTOR_LEFT);
  motor_rot_rel(-90);
  motors_stop();
  int facingRight = 0;
  lineSearching = 1;
  while (lineSearching && !pid_line_detect())
  {
    motors_move(EDGE_SPEED);
    delay_start(EDGE_DELAY);
    motor_rot_rel(facingRight ? -160 : 160);
    facingRight = facingRight ? 0 : 1;
  }
}
void nav_stop_search_line ()
Stop the line searching algorithm.
Definition at line 49 of file line_search.c.
References lineSearching.
{
  lineSearching = 0;
}
void RIT_IRQHandler ()
Definition at line 23 of file line_search.c.
References pid_check().
{
  RIT_GetIntStatus(LPC_RIT);
  pid_check();
}
Variable Documentation
int lineSearching = 0 static
Definition at line 20 of file line_search.c.
Referenced by nav_search_line(), and nav_stop_search_line().