Team Rocket Robotics: main_test_line.c File Reference
main_test_line.c File Reference
#include <lpc17xx_rit.h>
#include "motor.h"
#include "ir.h"
#include "uart.h"
#include "debug.h"
#include "wall_follow.h"
#include "config.h"
#include "gpio.h"
#include "pid.h"
#include "advanced_movement.h"
#include "coordinate.h"
#include "rit.h"
#include "line_sensors.h"
#include "utilities.h"
#include "delay.h"
Functions
void init ()
All system Initialisation.
void main_line_turn ()
void main_line_follow ()
void main_hold ()
void main ()
Variables
short int LINE_FOUND_FLAG = 0
short int MODE_RUNNING_FLAG = 0
short int LINE_TURN_FLAG = 0
uint16_t sensors [5]
int temp
Function Documentation
void init ()
All system Initialisation.
Definition at line 26 of file main_test_line.c.
References dbg_printf(), encoder_rpm_init(), gpio_button_wait(), gpio_init(), gpio_int_enable(), ir_init(), LED_ALL, led_off(), line_autocalibrate(), motors_stop(), mouse_setup(), and uart_init().
{
    debug_frmwrk_init();
    uart_init();
    ir_init();
    gpio_init();
    gpio_int_enable();
    //mouse_setup();
    line_autocalibrate();
    //RIT_Start(1000);
}
void main ()
Definition at line 89 of file main_test_line.c.
References init(), main_hold(), main_line_follow(), and pid_set().
{
    init();
    main_hold();
    pid_set();
    main_line_follow();
}
void main_hold ()
Definition at line 82 of file main_test_line.c.
References gpio_button_read().
Referenced by main().
{
    while(gpio_button_read());
}
void main_line_follow ()
Definition at line 68 of file main_test_line.c.
References main_line_turn(), MODE_RUNNING_FLAG, pid_run(), and pid_turn_flg().
Referenced by main().
{
    if(MODE_RUNNING_FLAG) {
        return;
    }
    MODE_RUNNING_FLAG   = 1;
    do {
        pid_run();
        main_line_turn();
        } while( pid_turn_flg());
}
void main_line_turn ()
Definition at line 38 of file main_test_line.c.
References MOTOR_LEFT, MOTOR_RIGHT, motor_set(), motors_stop(), pid_set(), pid_turn_detect(), pid_turn_flg(), and play_music().
Referenced by main_line_follow().
{
    if (pid_turn_flg() == 1) {
        play_music("!O6 T70 L6 V10 MS a8");
        while(!pid_turn_detect()) {
            motor_set(MOTOR_LEFT,-30);
            motor_set(MOTOR_RIGHT,30);
            //delay_start(400);
        }
        pid_set();
    }
     else if (pid_turn_flg() == 2) {
         play_music("!O6 T70 L6 V10 MS a8 a8");
        while(!pid_turn_detect()) {
            motor_set(MOTOR_LEFT,  30);
            motor_set(MOTOR_RIGHT,-30);
            //delay_start(400);
        }
        pid_set();
    }
    motors_stop();
}
Variable Documentation
short int LINE_FOUND_FLAG = 0
Definition at line 20 of file main_test_line.c.
short int LINE_TURN_FLAG = 0
Definition at line 22 of file main_test_line.c.
short int MODE_RUNNING_FLAG = 0
Definition at line 21 of file main_test_line.c.
Referenced by main_line_follow().
uint16_t sensors[5]
Definition at line 23 of file main_test_line.c.
Referenced by pid_line_detect(), pid_read_sensors(), and pid_turn_detect().
int temp
Definition at line 24 of file main_test_line.c.
Referenced by lcd_printf(), and line_read_position().