Team Rocket Robotics: main.h File Reference
main.h File Reference
#include "advanced_movement.h"
#include "coordinate.h"
#include "delay.h"
#include "debug.h"
#include "gpio.h"
#include "ir.h"
#include "lcd.h"
#include "led.h"
#include "line_sensors.h"
#include "motor.h"
#include "mouse.h"
#include "pid.h"
#include "uart.h"
#include "utilities.h"
#include "wall_follow.h"
#include "test/fufu_test.h"
Functions
void init ()
All system Initialisation.
void test ()
Test function.
void bullet_point_1_and_2 ()
Tasks in bullet point 1 and 2.
void bullet_point_3 ()
Tasks in bullet point 3.
void bullet_point_4 ()
Tasks in bullet point 4.
void docking_station_1 ()
Go to docking station 1.
void docking_station_2 ()
Go to docking station 2.
void nav_line_turn ()
Handling turns in line following.
void nav_line_follow ()
Wrapper for line following code.
Function Documentation
void bullet_point_1_and_2 ()
Tasks in bullet point 1 and 2.
Definition at line 55 of file main.c.
References motors_move(), nav_follow_wall(), SPEED_LIMIT, and WALL_RIGHT.
Referenced by main().
{
    motors_move(SPEED_LIMIT);
    nav_follow_wall(WALL_RIGHT);
}
void bullet_point_3 ()
Tasks in bullet point 3.
Definition at line 61 of file main.c.
References coordinate_read(), delay_start(), lcd_print_coordinate(), motor_rot_rel(), and move_forward.
{
    move_forward(200);
    delay_start(1000);
    motor_rot_rel(90);
    delay_start(1000);
    move_forward(100);
    delay_start(1000);
    motor_rot_rel(-90);
    lcd_print_coordinate(coordinate_read());
}
void bullet_point_4 ()
Tasks in bullet point 4.
Definition at line 73 of file main.c.
References gpio_button_wait(), line_autocalibrate(), nav_line_follow(), and pid_set().
{
    line_autocalibrate();
    gpio_button_wait();
    pid_set();
    #ifdef ENHANCED_TURN
    nav_line_follow();
    #endif
}
void docking_station_1 ()
Go to docking station 1.
This is done via pure dead reckoning, trolololol.
Definition at line 86 of file main.c.
References delay_start(), motor_rot_rel(), and move_forward.
{
    move_forward(500);
    delay_start(1000);
    motor_rot_rel(-90);
    move_forward(50);
    motor_rot_rel(-90);
}
void docking_station_2 ()
Go to docking station 2.
This is never going to work, Ah well...
Definition at line 98 of file main.c.
References delay_start(), motor_rot_rel(), and move_forward.
{
    move_forward(900);
    delay_start(1000);
    motor_rot_rel(90);
    move_forward(70);
    motor_rot_rel(90);
}
void init ()
All system Initialisation.
Definition at line 39 of file main.c.
References dbg_printf(), encoder_rpm_init(), gpio_button_wait(), gpio_init(), gpio_int_enable(), ir_init(), LED_ALL, led_off(), line_autocalibrate(), motors_stop(), mouse_setup(), and uart_init().
Referenced by main().
{
    debug_frmwrk_init();
    gpio_init();
    gpio_int_enable();
    ir_init();
    uart_init();
    encoder_rpm_init();
    mouse_setup();
    led_off(LED_ALL);
    motors_stop();
    dbg_printf("System initialised.\n\rWelcome to HAPR Spring Term Project\n\r");
    gpio_button_wait();
}
void nav_line_follow ()
Wrapper for line following code.
Referenced by bullet_point_4().
void nav_line_turn ()
Handling turns in line following.
void test ()
Test function.