Team Rocket Robotics: motor.c File Reference
motor.c File Reference
Polulu motor controller.
#include "config.h"
#include "debug.h"
#include "uart.h"
#include "delay.h"
#include "coordinate.h"
#include "motor.h"
Macros
#define L_FWD 0xC1
#define L_REV 0xC2
#define R_FWD 0xC5
#define R_REV 0xC6
Functions
void motor_bias_set (Motor motor, float n)
set motor bias
void motor_bias_disable_all ()
disable motor bias
void motor_bias_reset_all ()
reset motor bias
void internal_motor_send (Motor motor, int n)
private function: send a command to motor
static void internal_motor_rotate (volatile short angle)
private function: command the motor to rotate
static int internal_limiter (int n)
Speed limiter.
void motor_set (Motor motor, int n)
Set motor speed.
int motor_read (Motor motor)
Read motor speed.
void motors_stop ()
Stop both motors.
void motors_move (int n)
Move both motors.
void motor_rot_rel (short angle)
rotate the Pololu bot for arbitary angle
void motor_rot_abs (short target)
rotate the Pololu bot to an absolute bearing
void motor_angle_rest ()
reset the vehicle angle record
void motor_angle_sync (int n)
sync the motor.c angle record with coordinate.c
int motor_angle ()
get current angle of the vehicle
Variables
static short g_left_speed = 0
static short g_right_speed = 0
static volatile int g_angle = 0
static float LEFT_BIAS = LEFT_BIAS_BASE
static float RIGHT_BIAS = RIGHT_BIAS_BASE
Detailed Description
Polulu motor controller.
Author
Sam Gamble (typed up the command byte definition, created the 1st version, which is now the internal_motor_send function.)
Oliver Loftus (minor name changes related to function names.)
Fufu Fang (rewrote everything, because of people's feature demands.)
Definition in file motor.c.
Macro Definition Documentation
#define L_FWD 0xC1
Definition at line 17 of file motor.c.
Referenced by internal_motor_send().
#define L_REV 0xC2
Definition at line 18 of file motor.c.
Referenced by internal_motor_send().
#define R_FWD 0xC5
Definition at line 19 of file motor.c.
Referenced by internal_motor_send().
#define R_REV 0xC6
Definition at line 20 of file motor.c.
Referenced by internal_motor_send().
Function Documentation
static int internal_limiter (int n) static
Speed limiter.
Clip off speed that is too fast.
Definition at line 196 of file motor.c.
References SPEED_LIMIT.
Referenced by motor_set(), and motors_move().
{
    int s = 1;
    if (n < 0) {
        s = -1;
        n = -n;
    }
    if (n > SPEED_LIMIT) {
        n = SPEED_LIMIT;
    }
    n = n * s;
    return n;
}
static void internal_motor_rotate (volatile short angle) static
private function: command the motor to rotate
Warning
This function does not modify the internal g_angle record.
Definition at line 93 of file motor.c.
References dbg_printf(), delay_start(), g_angle, INERTIA_A, INERTIA_B, internal_motor_send(), MOTOR_LEFT, MOTOR_RIGHT, motors_stop(), and ROTATION_SPEED.
Referenced by motor_rot_rel().
{
    enum Direction {Clockwise, Anticlockwise};
    enum Direction direction;
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Internal: Entering, Rotating %d \n\r", angle);
    #endif
    /* Defensive programming, sanity check */
    if (angle == 0) {
        return;
    }
    #ifdef TIMED_ROTATION
        int delay = (float) angle / 180 * ROTATION_TIME;
        delay += ROTATION_WARMUP;
    #endif
    if (angle > 0) {
        direction = Clockwise;
        internal_motor_send(MOTOR_LEFT, ROTATION_SPEED);
        internal_motor_send(MOTOR_RIGHT, -ROTATION_SPEED);
    } else {
        direction = Anticlockwise;
        internal_motor_send(MOTOR_LEFT, -ROTATION_SPEED);
        internal_motor_send(MOTOR_RIGHT, ROTATION_SPEED);
    }
    #ifdef TIMED_ROTATION
        if (delay < 0) {
            delay = -delay;
        }
        delay_start(delay);
    #endif
    #ifdef COORD_ROTATION
        /* deviation formula is : 0.9x+(0.014x)^2, by empirical observation */
        int target = g_angle + angle * INERTIA_A + (angle * INERTIA_B) * (angle * INERTIA_B);
        //dbg_printf("Motor: Internal: Fresh Target: %d\r\n", target);
        int roll_over = target / 360;
        target %= 360;
        if (target < 0 && direction == Anticlockwise) {
            target += 360;
            roll_over = 1;
        }
        #ifdef MOTOR_DEBUG
            dbg_printf("Motor: Internal: Starting: Current %d, Target %d, Roll_over %d\r\n", g_angle, target, roll_over);
        #endif
        if (direction == Clockwise) {
            if(!roll_over) {
                while (g_angle < target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Clockwise, !roll_over: Target %d\r\n", target);
                    #endif
                }
            } else {
                while (g_angle > target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Clockwise, roll_over(1): Target %d\r\n", target);
                    #endif
                }
                while (g_angle < target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Clockwise, roll_over(2): Target %d\r\n", target);
                    #endif
                }
            }
        } else {
            if(!roll_over) {
                while (g_angle > target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Clockwise, !roll_over: Target %d\r\n", target);
                    #endif
                }
            } else {
                while (g_angle < target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Anticlockwise, roll_over(1): Target %d\r\n", target);
                    #endif
                }
                while (g_angle > target) {
                    #ifdef MOTOR_DEBUG
                    dbg_printf("Motor: Anticlockwise, roll_over(2): Target %d\r\n", target);
                    #endif
                }
            }
        }
    #endif
    motors_stop();
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Internal: Exiting\r\n", target);
    #endif
}
void internal_motor_send (Motor motor, int n)
private function: send a command to motor
Warning
This function has NO speed limit.
The lack of speed limit is to allow the robot to rotate faster.
Definition at line 56 of file motor.c.
References g_left_speed, g_right_speed, L_FWD, L_REV, LEFT_BIAS, MOTOR_LEFT, R_FWD, R_REV, RIGHT_BIAS, and uart_send_blk().
Referenced by adv_motors_rpm(), internal_motor_rotate(), and motor_set().
{
    char command[2];
    uint8_t *data = (uint8_t *) command;
    if (n > 0) {
        if (motor == MOTOR_LEFT) {
            command[0] = L_FWD;
            g_left_speed = n;
            n = (float) n * LEFT_BIAS;
        } else {
            command[0] = R_FWD;
            g_right_speed = n;
            n = (float) n * RIGHT_BIAS;
        }
    } else {
        /* turn negative n possitive for the 2nd command byte */
        n = -n;
        if (motor == MOTOR_LEFT) {
            command[0] = L_REV;
            g_left_speed = -n;
            n = (float) n * LEFT_BIAS;
        } else {
            command[0] = R_REV;
            g_right_speed = -n;
            n = (float) n * RIGHT_BIAS;
        }
    }
    command[1] = n;
    uart_send_blk(data, 2);
}
int motor_angle ()
get current angle of the vehicle
Note
this angle record might be different to the one in coordinate.c
Returns
the current angle of the motor
Definition at line 326 of file motor.c.
References dbg_printf(), and g_angle.
{
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Angle: %d \n\r", g_angle);
    #endif
    return g_angle;
}
void motor_angle_rest ()
reset the vehicle angle record
Definition at line 313 of file motor.c.
References g_angle.
{
    g_angle = 0;
}
void motor_angle_sync (int n)
sync the motor.c angle record with coordinate.c
Definition at line 318 of file motor.c.
References dbg_printf(), and g_angle.
Referenced by coordinate_update().
{
    g_angle = n;
    #ifdef MOTOR_DEBUG
        dbg_printf("Current %d \n\r", g_angle);
    #endif
}
void motor_bias_disable_all ()
disable motor bias
set LEFT_BIAS and RIGHT_BIAS to 1.
Definition at line 38 of file motor.c.
References LEFT_BIAS, and RIGHT_BIAS.
{
    LEFT_BIAS = 1;
    RIGHT_BIAS = 1;
}
void motor_bias_reset_all ()
reset motor bias
set LEFT_BIAS to LEFT_BIAS_BASE, and RIGHT_BIAS to RIGHT_BIAS_BASE.
Definition at line 44 of file motor.c.
References LEFT_BIAS, LEFT_BIAS_BASE, RIGHT_BIAS, and RIGHT_BIAS_BASE.
{
    LEFT_BIAS = LEFT_BIAS_BASE;
    RIGHT_BIAS = RIGHT_BIAS_BASE;
}
void motor_bias_set (Motor motor, float n)
set motor bias
set extra motor bias on top of the bias set by calibration, so the final bias depending on motor is LEFT_BIAS_BASE + n or RIGHT_BIAS_BASE+n.
Parameters
[in] motor the motor to set
[in] n the extra bias to set
Definition at line 29 of file motor.c.
References LEFT_BIAS, LEFT_BIAS_BASE, MOTOR_LEFT, RIGHT_BIAS, and RIGHT_BIAS_BASE.
{
    if (motor == MOTOR_LEFT) {
        LEFT_BIAS = LEFT_BIAS_BASE + n;
    } else {
        RIGHT_BIAS = RIGHT_BIAS_BASE + n;
    }
}
int motor_read (Motor motor)
Read motor speed.
Returns the current motor speed from a static int variable.
Parameters
motor either LEFT or RIGHT
Definition at line 222 of file motor.c.
References g_left_speed, g_right_speed, and MOTOR_LEFT.
Referenced by adv_motors_rpm(), encoder_update(), and nav_follow_wall().
{
    if (motor == MOTOR_LEFT) {
        return g_left_speed;
    } else {
        return g_right_speed;
    }
}
void motor_rot_abs (short angle)
rotate the Pololu bot to an absolute bearing
Parameters
angle the angle of the absolute bearing
Definition at line 285 of file motor.c.
References dbg_printf(), g_angle, and motor_rot_rel().
Referenced by adv_move(), adv_move_pid(), adv_move_pid_polar(), and adv_move_polar().
{
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Abs: Target = %d \n\r", target);
    #endif
    /* handling weird inputs */
    if (target > 360) {
        target %= 360;
    }
    else if (target < 0) {
        target %= 360;
        target += 360;
    }
    /* defensive programming - normalise internal record */
    g_angle %= 360;
    /* rotation angle should never be over 180 degrees,
     * otherwise it is inefficient.                     */
    int rotation_angle = target - g_angle;
    if (rotation_angle > 180) {
        rotation_angle = -(360-target) - g_angle;
    }
    else if (rotation_angle < -180) {
        rotation_angle = (360-g_angle) + target;
    }
    motor_rot_rel(rotation_angle);
}
void motor_rot_rel (short angle)
rotate the Pololu bot for arbitary angle
In timed rotation mode, This function essential wraps around internal_motor_rotate. If the robot is to rotate above 360 degrees, it rotate back to 0 degree first, then rotate to the resulting angle.
The robot can rotate back to the starting position quite accurately by rotating in the reverse direction for the same amount of time. However asking the robot to rotate 360 degrees does not result in accurate 360 degrees rotation.
Definition at line 254 of file motor.c.
References dbg_printf(), g_angle, and internal_motor_rotate().
Referenced by bullet_point_3(), docking_station_1(), docking_station_2(), motor_rot_abs(), and nav_search_line().
{
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Rel: Rotating %d \n\r", angle);
    #endif
    #ifdef TIMED_ROTATION
        /* Code for rotating back to the starting position */
        int new_angle = g_angle + angle;
        int full_rotation = new_angle / 360;
        if (full_rotation) {
            internal_motor_rotate(-g_angle);
            g_angle = 0;
            angle = new_angle % 360;
        }
    #endif
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Rel: Calling %d \n\r", angle);
    #endif
    internal_motor_rotate((volatile short)angle);
    #ifdef TIMED_ROTATION
        g_angle += angle;
    #endif
    #ifdef MOTOR_DEBUG
        dbg_printf("Motor: Rel: Rotated to: %d \n\r\n\r", g_angle);
    #endif
}
void motor_set (Motor motor, int n)
Set motor speed.
This essentially wraps around internal_motor_send. This allows motor_rotate to have a different speed limit to motor_set.
Definition at line 216 of file motor.c.
References internal_limiter(), and internal_motor_send().
Referenced by main_line_turn(), motors_move(), motors_stop(), nav_follow_wall(), and pid_motor_set().
{
    n=internal_limiter(n);
    internal_motor_send(motor, n);
}
void motors_move (int n)
Move both motors.
Parameters
[in] n the speed of motors
Definition at line 237 of file motor.c.
References internal_limiter(), MOTOR_LEFT, MOTOR_RIGHT, and motor_set().
Referenced by adv_motors_rpm(), adv_travel(), bullet_point_1_and_2(), nav_follow_wall(), and nav_search_line().
{
    n=internal_limiter(n);
    motor_set(MOTOR_LEFT, n);
    motor_set(MOTOR_RIGHT, n);
}
void motors_stop ()
Stop both motors.
Definition at line 231 of file motor.c.
References MOTOR_LEFT, MOTOR_RIGHT, and motor_set().
Referenced by adv_motors_rpm(), adv_move_pid_polar(), adv_travel(), init(), internal_motor_rotate(), main_line_turn(), nav_follow_wall(), and nav_search_line().
{
    motor_set(MOTOR_LEFT, 0);
    motor_set(MOTOR_RIGHT, 0);
}
Variable Documentation
volatile int g_angle = 0 static
Definition at line 24 of file motor.c.
Referenced by internal_motor_rotate(), motor_angle(), motor_angle_rest(), motor_angle_sync(), motor_rot_abs(), and motor_rot_rel().
short g_left_speed = 0 static
Definition at line 22 of file motor.c.
Referenced by internal_motor_send(), and motor_read().
short g_right_speed = 0 static
Definition at line 23 of file motor.c.
Referenced by internal_motor_send(), and motor_read().
float LEFT_BIAS = LEFT_BIAS_BASE static
Definition at line 26 of file motor.c.
Referenced by internal_motor_send(), motor_bias_disable_all(), motor_bias_reset_all(), and motor_bias_set().
float RIGHT_BIAS = RIGHT_BIAS_BASE static
Definition at line 27 of file motor.c.
Referenced by internal_motor_send(), motor_bias_disable_all(), motor_bias_reset_all(), and motor_bias_set().