Team Rocket Robotics: mouse.h File Reference
mouse.h File Reference
header file for mouse module
#include <stdint.h>
#include "coordinate.h"
Functions
void mouse_callback (uint8_t button, int8_t l, int8_t t)
callback function for mouse movement
void mouse_attach ()
callback function for mouse attachment
void mouse_detach ()
callback function for mouse detachment
void TIMER2_IRQHandler ()
Interrupt Service Routine for Timer 2.
void mouse_setup ()
Setup the mouse subsystem.
Detailed Description
header file for mouse module
Author
Fufu Fang (wrote the whole file)
Definition in file mouse.h.
Function Documentation
void mouse_attach ()
callback function for mouse attachment
Definition at line 142 of file mouse.c.
References dbg_printf().
Referenced by mouse_setup().
{
    dbg_printf("Mouse attached\r\n");
}
void mouse_callback (uint8_t button, int8_t l, int8_t t)
callback function for mouse movement
The mouse always move forwards in one axis, and rotate on another axis, hence it works in polar coordinate.
Definition at line 114 of file mouse.c.
References coordinate_update(), L_PER_CM, Polar::r, SHIFT_L, SHIFT_T, Polar::t, T_PER_DEGREE, and toRadian().
Referenced by mouse_setup().
{
    (void) button;
    /* All correction factors are in x_per_reading format. */
    float tempt_t = ((float)t - 1/SHIFT_T) / T_PER_DEGREE;
    float d_l = ((float)l - 1/SHIFT_L) / L_PER_CM;
#ifdef MOUSE_DEBUG
    /* populating debugging record */
    dbg_record.raw_l += l;
    dbg_record.raw_t += t;
    dbg_record.cal_l += d_l;
    dbg_record.cal_t += tempt_t;
    dbg_record.count += 1;
//     dbg_printf("Mouse.c:  ");
//     dbg_print_mouse(dbg_record);
#endif
    float d_t = toRadian(tempt_t);
    Polar update;
    update.r = d_l;
    /*Clockwise rotation should have a positive value */
    update.t = -d_t;
    coordinate_update(update);
}
void mouse_detach ()
callback function for mouse detachment
Definition at line 147 of file mouse.c.
References dbg_printf().
Referenced by mouse_setup().
{
    dbg_printf("Mouse detached\r\n");
}
void mouse_setup ()
Setup the mouse subsystem.
setup the function pointers for Jamie's library, then initialise the timer using a private function.
Definition at line 152 of file mouse.c.
References dbg_printf(), mouse_attach(), mouse_callback(), mouse_detach(), mouse_init(), and mouse_timer_init().
Referenced by init().
{
    #ifdef WHEEL_ENCODER
        dbg_printf("The robot is set to use wheel encoder, ");
        dbg_printf("you can disable it in config.h.");
        dbg_printf("The mouse is NOT configured!\r\n");
        return;
    #endif
    mouse_init(mouse_callback, mouse_attach, mouse_detach);
    mouse_timer_init();
}
void TIMER2_IRQHandler (void)
Interrupt Service Routine for Timer 2.
This ISR polls the mouse.
This interrupt service routine polls the mouse.
Definition at line 100 of file mouse.c.
References LED_2, led_off(), led_on(), and mouse_poll().
{
    led_on(LED_2);
    mouse_poll();
    led_off(LED_2);
    TIM_ClearIntPending(LPC_TIM2, TIM_MR2_INT);
}