Team Rocket Robotics: mouse.c File Reference
mouse.c File Reference
mouse module source code
#include <math.h>
#include <lpc17xx_timer.h>
#include "KeyboardHost.h"
#include "config.h"
#include "common.h"
#include "lcd.h"
#include "led.h"
#include "debug.h"
#include "coordinate.h"
#include "mouse.h"
Macros
#define SHIFT_L -0.466
#define SHIFT_T -14.1
#define T_PER_DEGREE 45
#define L_PER_CM 395
Functions
static void mouse_timer_init ()
Private function: set up the mouse timer.
void TIMER2_IRQHandler (void)
Interrupt Service Routine for Timer 2.
void mouse_callback (uint8_t button, int8_t l, int8_t t)
callback function for mouse movement
void mouse_attach ()
callback function for mouse attachment
void mouse_detach ()
callback function for mouse detachment
void mouse_setup ()
Setup the mouse subsystem.
Detailed Description
mouse module source code
This module handles everything that's got to do with the mouse.
Note
Correction factors for the mouse:
SHIFT_T corrects for the bias in rotation,
SHIFT_L corrects for the bias in distance,
T_PER_DEGREE is the T reading from the mouse when the vehicle rotate about its centre for 180 degrees
L_PER_CM is the distance the R reading from the mouse when the vehicle moves in a straight line for 1 meter.
Author
Fufu Fang (wrote the whole thing)
Nathan Bartram (for trying but failing to link our binary to Jamie's library)
Sam Gamble (for trying to but failing to link our binary to Jamie's library)
Definition in file mouse.c.
Macro Definition Documentation
#define L_PER_CM 395
Definition at line 36 of file mouse.c.
Referenced by mouse_callback().
#define SHIFT_L -0.466
Definition at line 33 of file mouse.c.
Referenced by mouse_callback().
#define SHIFT_T -14.1
Definition at line 34 of file mouse.c.
Referenced by mouse_callback().
#define T_PER_DEGREE 45
Definition at line 35 of file mouse.c.
Referenced by mouse_callback().
Function Documentation
void mouse_attach ()
callback function for mouse attachment
Definition at line 142 of file mouse.c.
References dbg_printf().
Referenced by mouse_setup().
{
    dbg_printf("Mouse attached\r\n");
}
void mouse_callback (uint8_t button, int8_t l, int8_t t)
callback function for mouse movement
The mouse always move forwards in one axis, and rotate on another axis, hence it works in polar coordinate.
Definition at line 114 of file mouse.c.
References coordinate_update(), L_PER_CM, Polar::r, SHIFT_L, SHIFT_T, Polar::t, T_PER_DEGREE, and toRadian().
Referenced by mouse_setup().
{
    (void) button;
    /* All correction factors are in x_per_reading format. */
    float tempt_t = ((float)t - 1/SHIFT_T) / T_PER_DEGREE;
    float d_l = ((float)l - 1/SHIFT_L) / L_PER_CM;
#ifdef MOUSE_DEBUG
    /* populating debugging record */
    dbg_record.raw_l += l;
    dbg_record.raw_t += t;
    dbg_record.cal_l += d_l;
    dbg_record.cal_t += tempt_t;
    dbg_record.count += 1;
//     dbg_printf("Mouse.c:  ");
//     dbg_print_mouse(dbg_record);
#endif
    float d_t = toRadian(tempt_t);
    Polar update;
    update.r = d_l;
    /*Clockwise rotation should have a positive value */
    update.t = -d_t;
    coordinate_update(update);
}
void mouse_detach ()
callback function for mouse detachment
Definition at line 147 of file mouse.c.
References dbg_printf().
Referenced by mouse_setup().
{
    dbg_printf("Mouse detached\r\n");
}
void mouse_setup ()
Setup the mouse subsystem.
setup the function pointers for Jamie's library, then initialise the timer using a private function.
Definition at line 152 of file mouse.c.
References dbg_printf(), mouse_attach(), mouse_callback(), mouse_detach(), mouse_init(), and mouse_timer_init().
Referenced by init().
{
    #ifdef WHEEL_ENCODER
        dbg_printf("The robot is set to use wheel encoder, ");
        dbg_printf("you can disable it in config.h.");
        dbg_printf("The mouse is NOT configured!\r\n");
        return;
    #endif
    mouse_init(mouse_callback, mouse_attach, mouse_detach);
    mouse_timer_init();
}
static void mouse_timer_init () static
Private function: set up the mouse timer.
This function essentially initialise the timer and the associated interrupt settings.
Bug:
The interrupt priority is currently the same as timer 3!!!
Definition at line 62 of file mouse.c.
Referenced by mouse_setup().
{
    TIM_TIMERCFG_Type timer_config;
    TIM_MATCHCFG_Type match_config;
    /* The timer is configured to tick once every 1000 microseconds (1ms) */
    timer_config.PrescaleOption = TIM_PRESCALE_USVAL;
    timer_config.PrescaleValue = 500;
    /* Interrupt is triggered once every 1 ticks (0.5ms) */
    match_config.MatchValue = 1;
    /* Using timer 2 */
    match_config.MatchChannel = 2;
    match_config.IntOnMatch = TRUE;
    match_config.ResetOnMatch = TRUE;
    match_config.StopOnMatch = FALSE;
    match_config.ExtMatchOutputType = TIM_EXTMATCH_NOTHING;
    /* Initialise timer */
    TIM_Init(LPC_TIM2, TIM_TIMER_MODE, &timer_config);
    /* Configure interrupt triggering */
    TIM_ConfigMatch(LPC_TIM2, &match_config);
    /* Set interrupt priority, preemption = 1, sub-priority = 1 */
    NVIC_SetPriority(TIMER2_IRQn, ((0x01 << 3) | 0x01));
    /* Enable interrupt for timer 2 */
    NVIC_EnableIRQ(TIMER2_IRQn);
    /* Start timer 2 */
    TIM_Cmd(LPC_TIM2, ENABLE);
}
void TIMER2_IRQHandler (void)
Interrupt Service Routine for Timer 2.
This interrupt service routine polls the mouse.
Definition at line 100 of file mouse.c.
References LED_2, led_off(), led_on(), and mouse_poll().
{
    led_on(LED_2);
    mouse_poll();
    led_off(LED_2);
    TIM_ClearIntPending(LPC_TIM2, TIM_MR2_INT);
}