Team Rocket Robotics: odometry.c File Reference
odometry.c File Reference
Wheel encoder based odometry module (source)
#include <lpc17xx_timer.h>
#include "advanced_movement.h"
#include "common.h"
#include "coordinate.h"
#include "debug.h"
#include "led.h"
#include "motor.h"
#include "odometry.h"
Macros
#define WHEEL_BASE 8.7
#define TRIGGER 2
#define L_PER_CM 1.194
#define R_PER_CM 1.194
#define CLICK_PER_WHEEL 12
#define SAMPLE_RATE 0.5
Functions
static void encoder_submit ()
submit wheel encoder's data
static void encoder_rpm_calculate ()
static void encoder_rpm_clear ()
clear encoder rpm click count
void encoder_clear ()
clear encoder distance click count
void encoder_update (Encoder encoder)
increase the internal encoder count
void encoder_rpm_init ()
Initialise the timer for odometer rpm calculation.
void TIMER3_IRQHandler ()
Interrupt service routine for Timer 3.
float encoder_rpm (Encoder encoder)
return motor rpm
void encoder_rpm_off ()
turn off motor rpm timer
Variables
static int g_left_count = 0
static int g_right_count = 0
static int g_total_count = 0
static int g_left_rpm_count = 0
static int g_right_rpm_count = 0
static RPM g_rpm = {0, 0}
Detailed Description
Wheel encoder based odometry module (source)
Author
Fufu Fang (Personal part of the project)
Definition in file odometry.c.
Macro Definition Documentation
#define CLICK_PER_WHEEL 12
Definition at line 32 of file odometry.c.
Referenced by encoder_rpm_calculate().
#define L_PER_CM 1.194
Definition at line 29 of file odometry.c.
Referenced by encoder_submit().
#define R_PER_CM 1.194
Definition at line 30 of file odometry.c.
Referenced by encoder_submit().
#define SAMPLE_RATE 0.5
Definition at line 35 of file odometry.c.
Referenced by encoder_rpm_calculate().
#define TRIGGER 2
Definition at line 21 of file odometry.c.
Referenced by encoder_update().
#define WHEEL_BASE 8.7
Definition at line 18 of file odometry.c.
Referenced by encoder_submit().
Function Documentation
void encoder_clear ()
clear encoder distance click count
clear encoder record
Definition at line 90 of file odometry.c.
References dbg_printf(), g_left_count, g_right_count, and g_total_count.
Referenced by encoder_update().
{
    g_left_count = 0;
    g_right_count = 0;
    g_total_count = 0;
    #ifdef ODOMETRY_DBG
        dbg_printf("Odometry.c:\tCounters cleared!\r\n");
    #endif
}
float encoder_rpm (Encoder encoder)
return motor rpm
Definition at line 186 of file odometry.c.
References RPM::left, LEFT_ENCODER, and RPM::right.
{
    if (encoder == LEFT_ENCODER) {
        return g_rpm.left;
    } else {
        return g_rpm.right;
    }
}
static void encoder_rpm_calculate () static
Definition at line 65 of file odometry.c.
References CLICK_PER_WHEEL, dbg_printf(), g_left_rpm_count, g_right_rpm_count, RPM::left, RPM::right, and SAMPLE_RATE.
Referenced by TIMER3_IRQHandler().
{
    g_rpm.left = (float)g_left_rpm_count/CLICK_PER_WHEEL/SAMPLE_RATE*60;
    g_rpm.right = (float)g_right_rpm_count/CLICK_PER_WHEEL/SAMPLE_RATE*60;
    #ifdef RPM_DBG
        dbg_printf("Odometry.c:\tLeft RPM: %f\tRight RPM: %f\r\n",
                   g_rpm.left, g_rpm.right);
    #endif
}
static void encoder_rpm_clear () static
clear encoder rpm click count
Definition at line 78 of file odometry.c.
References dbg_printf(), g_left_rpm_count, and g_right_rpm_count.
Referenced by TIMER3_IRQHandler().
{
    g_left_rpm_count = 0;
    g_right_rpm_count = 0;
    #ifdef ODOMETRY_DBG
        dbg_printf("Odometry.c:\tRPM counters cleared!\r\n");
    #endif
}
void encoder_rpm_init ()
Initialise the timer for odometer rpm calculation.
This function essentially initialise the timer and the associated interrupt settings.
Definition at line 138 of file odometry.c.
Referenced by init().
{
    TIM_TIMERCFG_Type timer_config;
    TIM_MATCHCFG_Type match_config;
    /* The timer is configured to tick once every 1000 microseconds (1ms) */
    timer_config.PrescaleOption = TIM_PRESCALE_USVAL;
    timer_config.PrescaleValue = 1000;
    /* Interrupt is triggered once every 100 ticks (500ms or 0.5s) */
    match_config.MatchValue = 500;
    /* Using timer 3 */
    match_config.MatchChannel = 3;
    match_config.IntOnMatch = TRUE;
    match_config.ResetOnMatch = TRUE;
    match_config.StopOnMatch = FALSE;
    match_config.ExtMatchOutputType = TIM_EXTMATCH_NOTHING;
    /* Initialise timer */
    TIM_Init(LPC_TIM3, TIM_TIMER_MODE, &timer_config);
    /* Configure interrupt triggering */
    TIM_ConfigMatch(LPC_TIM3, &match_config);
    /* Enable interrupt for timer 3 */
    NVIC_EnableIRQ(TIMER3_IRQn);
    /* Start timer 3 */
    TIM_Cmd(LPC_TIM3, ENABLE);
}
void encoder_rpm_off ()
turn off motor rpm timer
Definition at line 195 of file odometry.c.
{
    TIM_DeInit(LPC_TIM3);
}
static void encoder_submit () static
submit wheel encoder's data
calculate the distance moved and the angle changed, call coordinate_update with the data.
Definition at line 51 of file odometry.c.
References coordinate_update(), dbg_printf(), g_left_count, g_right_count, L_PER_CM, Polar::r, R_PER_CM, Polar::t, toDegree(), and WHEEL_BASE.
Referenced by encoder_update().
{
    float left_cm = (float)g_left_count / L_PER_CM;
    float right_cm = (float)g_right_count / R_PER_CM;
    Polar update;
    update.r = (left_cm + right_cm) /2;
    update.t = (left_cm - right_cm) / WHEEL_BASE;
    coordinate_update(update);
    #ifdef ODOMETRY_DBG
        dbg_printf("Odometry.c:\tleft_cm: %f\tright_cm: %f\tdistance: %f\tangle: %f\r\n",
                   left_cm, right_cm, update.r, toDegree(update.t));
    #endif
}
void encoder_update (Encoder encoder)
increase the internal encoder count
Definition at line 100 of file odometry.c.
References dbg_printf(), encoder_clear(), encoder_submit(), g_left_count, g_left_rpm_count, g_right_count, g_right_rpm_count, g_total_count, LEFT_ENCODER, MOTOR_LEFT, motor_read(), MOTOR_RIGHT, and TRIGGER.
Referenced by EINT3_IRQHandler().
{
    int motor_speed;
    g_total_count++;
    if (encoder == LEFT_ENCODER) {
        motor_speed = motor_read(MOTOR_LEFT);
        if (motor_speed > 0) {
            g_left_count++;
            g_left_rpm_count++;
        } else {
            g_left_count--;
            g_left_rpm_count--;
        }
    } else {
        motor_speed = motor_read(MOTOR_RIGHT);
        if (motor_speed > 0) {
            g_right_count++;
            g_right_rpm_count++;
        } else {
            g_right_count--;
            g_right_rpm_count--;
        }
    }
    if (g_total_count >= TRIGGER) {
        encoder_submit();
        encoder_clear();
    }
    #ifdef UPDATE_DBG
        dbg_printf("Odometry.c:\tleft_count: %d\tright_count: %d\ttotal_count: %d\r\n",
                   g_left_count, g_right_count, g_total_count);
    #endif
}
void TIMER3_IRQHandler ()
Interrupt service routine for Timer 3.
The interrupt service routine changes the time record, based on the execution mode.
Definition at line 174 of file odometry.c.
References adv_rpm_update(), encoder_rpm_calculate(), encoder_rpm_clear(), LED_3, led_off(), and led_on().
{
    led_on(LED_3);
    encoder_rpm_calculate();
    adv_rpm_update(g_rpm);
    encoder_rpm_clear();
    led_off(LED_3);
    TIM_ClearIntPending(LPC_TIM3, TIM_MR3_INT);
}
Variable Documentation
int g_left_count = 0 static
Definition at line 37 of file odometry.c.
Referenced by encoder_clear(), encoder_submit(), and encoder_update().
int g_left_rpm_count = 0 static
Definition at line 41 of file odometry.c.
Referenced by encoder_rpm_calculate(), encoder_rpm_clear(), and encoder_update().
int g_right_count = 0 static
Definition at line 38 of file odometry.c.
Referenced by encoder_clear(), encoder_submit(), and encoder_update().
int g_right_rpm_count = 0 static
Definition at line 42 of file odometry.c.
Referenced by encoder_rpm_calculate(), encoder_rpm_clear(), and encoder_update().
RPM g_rpm = {0, 0} static
Definition at line 44 of file odometry.c.
int g_total_count = 0 static
Definition at line 39 of file odometry.c.
Referenced by encoder_clear(), and encoder_update().