Team Rocket Robotics: odometry.h File Reference
odometry.h File Reference
Wheel encoder based odometery module (header file)
Data Structures
struct RPM
Motor RPM record structure.
Enumerations
enum Encoder { LEFT_ENCODER, RIGHT_ENCODER }
Functions
void encoder_clear ()
clear encoder record
void encoder_update (Encoder encoder)
increase the internal encoder count
void encoder_rpm_init ()
Initialise the timer for odometer rpm calculation.
void TIMER3_IRQHandler ()
Interrupt service routine for Timer 3.
float encoder_rpm (Encoder encoder)
return motor rpm
void encoder_rpm_off ()
turn off motor rpm timer
Detailed Description
Wheel encoder based odometery module (header file)
Author
Fufu Fang (Personal part of the project)
Definition in file odometry.h.
Enumeration Type Documentation
enum Encoder
Enumerator:
LEFT_ENCODER
RIGHT_ENCODER
Definition at line 15 of file odometry.h.
             {
    LEFT_ENCODER,
    RIGHT_ENCODER
} Encoder;
Function Documentation
void encoder_clear ()
clear encoder record
Definition at line 90 of file odometry.c.
References dbg_printf(), g_left_count, g_right_count, and g_total_count.
Referenced by encoder_update().
{
    g_left_count = 0;
    g_right_count = 0;
    g_total_count = 0;
    #ifdef ODOMETRY_DBG
        dbg_printf("Odometry.c:\tCounters cleared!\r\n");
    #endif
}
float encoder_rpm (Encoder encoder)
return motor rpm
Definition at line 186 of file odometry.c.
References RPM::left, LEFT_ENCODER, and RPM::right.
{
    if (encoder == LEFT_ENCODER) {
        return g_rpm.left;
    } else {
        return g_rpm.right;
    }
}
void encoder_rpm_init ()
Initialise the timer for odometer rpm calculation.
This function essentially initialise the timer and the associated interrupt settings.
Definition at line 138 of file odometry.c.
Referenced by init().
{
    TIM_TIMERCFG_Type timer_config;
    TIM_MATCHCFG_Type match_config;
    /* The timer is configured to tick once every 1000 microseconds (1ms) */
    timer_config.PrescaleOption = TIM_PRESCALE_USVAL;
    timer_config.PrescaleValue = 1000;
    /* Interrupt is triggered once every 100 ticks (500ms or 0.5s) */
    match_config.MatchValue = 500;
    /* Using timer 3 */
    match_config.MatchChannel = 3;
    match_config.IntOnMatch = TRUE;
    match_config.ResetOnMatch = TRUE;
    match_config.StopOnMatch = FALSE;
    match_config.ExtMatchOutputType = TIM_EXTMATCH_NOTHING;
    /* Initialise timer */
    TIM_Init(LPC_TIM3, TIM_TIMER_MODE, &timer_config);
    /* Configure interrupt triggering */
    TIM_ConfigMatch(LPC_TIM3, &match_config);
    /* Enable interrupt for timer 3 */
    NVIC_EnableIRQ(TIMER3_IRQn);
    /* Start timer 3 */
    TIM_Cmd(LPC_TIM3, ENABLE);
}
void encoder_rpm_off ()
turn off motor rpm timer
Definition at line 195 of file odometry.c.
{
    TIM_DeInit(LPC_TIM3);
}
void encoder_update (Encoder encoder)
increase the internal encoder count
Definition at line 100 of file odometry.c.
References dbg_printf(), encoder_clear(), encoder_submit(), g_left_count, g_left_rpm_count, g_right_count, g_right_rpm_count, g_total_count, LEFT_ENCODER, MOTOR_LEFT, motor_read(), MOTOR_RIGHT, and TRIGGER.
Referenced by EINT3_IRQHandler().
{
    int motor_speed;
    g_total_count++;
    if (encoder == LEFT_ENCODER) {
        motor_speed = motor_read(MOTOR_LEFT);
        if (motor_speed > 0) {
            g_left_count++;
            g_left_rpm_count++;
        } else {
            g_left_count--;
            g_left_rpm_count--;
        }
    } else {
        motor_speed = motor_read(MOTOR_RIGHT);
        if (motor_speed > 0) {
            g_right_count++;
            g_right_rpm_count++;
        } else {
            g_right_count--;
            g_right_rpm_count--;
        }
    }
    if (g_total_count >= TRIGGER) {
        encoder_submit();
        encoder_clear();
    }
    #ifdef UPDATE_DBG
        dbg_printf("Odometry.c:\tleft_count: %d\tright_count: %d\ttotal_count: %d\r\n",
                   g_left_count, g_right_count, g_total_count);
    #endif
}
void TIMER3_IRQHandler ()
Interrupt service routine for Timer 3.
The interrupt service routine changes the time record, based on the execution mode.
Definition at line 174 of file odometry.c.
References adv_rpm_update(), encoder_rpm_calculate(), encoder_rpm_clear(), LED_3, led_off(), and led_on().
{
    led_on(LED_3);
    encoder_rpm_calculate();
    adv_rpm_update(g_rpm);
    encoder_rpm_clear();
    led_off(LED_3);
    TIM_ClearIntPending(LPC_TIM3, TIM_MR3_INT);
}