Team Rocket Robotics: pid.c File Reference
pid.c File Reference
Line following code.
#include "line_sensors.h"
#include "motor.h"
#include "pid.h"
#include "debug.h"
#include "gpio.h"
#include "line_follow.h"
#include "advanced_movement.h"
Macros
#define SPEED_OFFSET 0
#define Kp 45
#define Ki 10000
#define Kd 500
#define Kp_l 45
#define Ki_l 10000
#define Kd_l 500
#define MIN_SPEED 3
#define MAX_SPEED 30
#define LINE_MISS_MAX 3
#define POLULU_PID
Functions
char pid_match_pattern (uint16_t *sensor)
int pid_turn_flg ()
int pid_turn_detect ()
Detecting of LEFT / RIGHT Turn at end of line.
void pid_read_sensors ()
int pid_line_detect ()
Line detection for the PID algorithm.
int pid_over_line ()
void pid_set ()
Set and Clear PID Flags used to track the current state of the PID loop.
void pid_clear ()
clear PID flag
int pid_check_running ()
Check if Line following is in PID LOOP.
void pid_exit_check ()
void pid_control_loop ()
void pid_run ()
Start Line following.
int pid_calc (int prop_current, int *prop_last, int *integral, int *derivative)
Factored out PID calculation function.
void pid_motor_set (int power_diff)
Set Motors move fwd based on PID result.
Variables
short int PID_FLAG = 0
short int PID_RUNNING = 0
short int TURN_FLG = 0
short int miss_counter = 0
short int hit_counter = 0
char sensor_pattern = 0
uint16_t sensors [5]
Detailed Description
Line following code.
Author
Sam Gamble
Definition in file pid.c.
Macro Definition Documentation
#define Kd 500
Definition at line 19 of file pid.c.
Referenced by pid_calc().
#define Kd_l 500
Definition at line 23 of file pid.c.
#define Ki 10000
Definition at line 18 of file pid.c.
Referenced by pid_calc().
#define Ki_l 10000
Definition at line 22 of file pid.c.
#define Kp 45
Definition at line 17 of file pid.c.
Referenced by pid_calc().
#define Kp_l 45
Definition at line 21 of file pid.c.
#define LINE_MISS_MAX 3
Definition at line 28 of file pid.c.
Referenced by pid_exit_check().
#define MAX_SPEED 30
Definition at line 25 of file pid.c.
#define MIN_SPEED 3
Definition at line 24 of file pid.c.
#define POLULU_PID
Definition at line 34 of file pid.c.
#define SPEED_OFFSET 0
Definition at line 16 of file pid.c.
Referenced by pid_motor_set().
Function Documentation
int pid_calc (int prop_current, int * prop_last, int * integral, int * derivative)
Factored out PID calculation function.
Warning
the params 'prop_last' 'integral' and 'derivative' are int pointers used to pass by reference. This is required for factoring out the PID algorithum because these values are cumulative (dependent on time).
Definition at line 382 of file pid.c.
References dbg_printf(), Kd, Ki, and Kp.
Referenced by adv_move_pid_polar().
{
    #ifdef DEBUG
    dbg_printf("last_proportional  %d\n\r", *prop_last);
    #endif
    *derivative = prop_current - *prop_last;
    *prop_last = prop_current;
    *integral += prop_current;
    int power_difference = (prop_current/Kp + *integral/Ki + *derivative * 2/Kd);
    #ifdef DEBUG
    dbg_printf("proportional       %d\n\r", prop_current);
    dbg_printf("integral           %d\n\r",*integral);
    dbg_printf("derivative         %d\n\r",*derivative);
    dbg_printf("power_difference   %d\n\r",power_difference);
    #endif
    return power_difference;
}
int pid_check_running ()
Check if Line following is in PID LOOP.
Note
running -> return 1, exited -> return 0
Definition at line 193 of file pid.c.
References PID_RUNNING.
{
    if(PID_RUNNING)
        return 1;
    else
        return 0;
}
void pid_clear ()
clear PID flag
It can cause PID algorithm to exit.
Definition at line 179 of file pid.c.
References dbg_printf(), nav_stop_follow_line(), PID_FLAG, and PID_RUNNING.
Referenced by pid_exit_check().
{
    #ifdef DEBUG
    dbg_printf("PID_FLAG = 0\n\r");
    #endif
    PID_FLAG = 0;
    PID_RUNNING = 0;
    #ifdef POLULU_PID
    nav_stop_follow_line();
    #endif
}
void pid_control_loop ()
Definition at line 244 of file pid.c.
References pid_exit_check(), PID_FLAG, PID_RUNNING, pid_turn_detect(), and TURN_FLG.
Referenced by pid_run().
{
    PID_RUNNING = 1;
    TURN_FLG    = 0;
    while(1){
        if(!PID_FLAG)
            return;
        pid_turn_detect();
        pid_exit_check();
    }
}
void pid_exit_check ()
Definition at line 219 of file pid.c.
References dbg_printf(), hit_counter, LINE_MISS_MAX, miss_counter, pid_clear(), and pid_over_line().
Referenced by pid_control_loop().
{
    #ifdef DEBUG
    dbg_printf("-Exit check-\n\r",miss_counter);
    #endif
    if (pid_over_line()){
        hit_counter++;
        miss_counter = 0;
    }
    else {
        hit_counter = 0;
        miss_counter++;
        if (miss_counter >= LINE_MISS_MAX) {
            pid_clear();
        }
    }
    #ifdef DEBUG
    dbg_printf("miss cnt = %d   hit cnt = %d\n\r",miss_counter,hit_counter);
    #endif
}
int pid_line_detect ()
Line detection for the PID algorithm.
Note
should only run on entry to the PID LOOP
Definition at line 128 of file pid.c.
References dbg_printf(), pid_read_sensors(), sensor_pattern, and sensors.
Referenced by nav_search_line().
{
    #ifdef DEBUG
    dbg_printf("-pid line detect-\n\r");
    #endif
    pid_read_sensors(sensor_pattern);
    if(sensor_pattern == 'B') {
        return 0;
    }
    if( sensors[0] == 1000
     || sensors[1] == 1000
     || sensors[2] == 1000
     || sensors[3] == 1000
     || sensors[4] == 1000) {
         return 1;
    }
    return 0;
}
char pid_match_pattern (uint16_t * sensor)
Note
Cases
'B' = Black line, all sensors dark
'F' = Follow, Line is under middle sensors
'L' = Left Turn detected, Line under middle sensors && leftmost sensor
'R' = Right turn detected ..
Definition at line 56 of file pid.c.
Referenced by pid_read_sensors().
{
    if ( sensor[0] > 900
      && sensor[1] > 900
      && sensor[2] > 900
      && sensor[3] > 900
      && sensor[4] > 900) {
        return 'B';   //solid black line, STOP!
    }
    if ( sensor[1] < 300
      && sensor[2] < 300
      && sensor[3] < 300) {
        return 'E';   // exit pattern
    }
    return 0;
}
void pid_motor_set (int power_diff)
Set Motors move fwd based on PID result.
Author
Sam Gamble
Warning
Requires #define 'SPEED_OFFSET',currently = 0 (will be set on testing)
Parameters
[in] power difference value (-30 .. +30) if above these values the motor speeds will be capped to (SPEED_OFFSET + SPEED_LIMIT)
Definition at line 403 of file pid.c.
References dbg_printf(), MOTOR_LEFT, MOTOR_RIGHT, motor_set(), SPEED_LIMIT, and SPEED_OFFSET.
Referenced by adv_move_pid_polar().
{
    short int l_speed  = 0;
    short int r_speed = 0;
    if( power_diff > SPEED_LIMIT ) {
        power_diff = SPEED_LIMIT;
    }
    if( power_diff < -SPEED_LIMIT ) {
        power_diff = -SPEED_LIMIT;
    }
    if(power_diff < 0) {
        l_speed  = (short int)(SPEED_OFFSET + SPEED_LIMIT +power_diff);
        r_speed = (short int)(SPEED_OFFSET + SPEED_LIMIT);
    } else {
        l_speed  = (short int)(SPEED_OFFSET + SPEED_LIMIT);
        r_speed = (short int)(SPEED_OFFSET + SPEED_LIMIT -power_diff);
    }
    motor_set(MOTOR_LEFT  ,l_speed);
    motor_set(MOTOR_RIGHT ,r_speed);
    #ifdef DEBUG
    dbg_printf("ADV_PID: L_Motor = %d,  R_Motor = %d" ,l_speed ,r_speed);
    #endif
}
int pid_over_line ()
Definition at line 149 of file pid.c.
References dbg_printf(), pid_read_sensors(), and sensor_pattern.
Referenced by pid_exit_check().
{
    #ifdef DEBUG
    dbg_printf("-pid over line detect-\n\r");
    #endif
    pid_read_sensors();
    if(sensor_pattern == 'B')
        return 0;
    if(sensor_pattern == 'E')
        return 0;
    return 1;
}
void pid_read_sensors ()
Definition at line 114 of file pid.c.
References dbg_printf(), line_read(), pid_match_pattern(), sensor_pattern, and sensors.
Referenced by pid_line_detect(), and pid_over_line().
{
    //line_calibrate_read(sensors);
    line_read(sensors);
    sensor_pattern = pid_match_pattern(sensors);
    #ifdef DEBUG
    dbg_printf( "Sensor Values %d %d %d %d %d\n\r"
    ,sensors[0], sensors[1],sensors[2],sensors[3],sensors[4]);
    dbg_printf("Sensor ptn: %c\n\r",sensor_pattern);
    #endif
}
void pid_run ()
Start Line following.
Note, will do NOTHING unless flags are set using either pid_check() or pid_set()
Definition at line 366 of file pid.c.
References dbg_printf(), pid_control_loop(), PID_FLAG, and PID_RUNNING.
Referenced by main_line_follow().
{
    #ifdef DEBUG
    dbg_printf("---pid run---\n\r");
    #endif
    if (PID_RUNNING || !PID_FLAG) return;
        pid_control_loop();
}
void pid_set ()
Set and Clear PID Flags used to track the current state of the PID loop.
Sets Flags which trigger line following.
Definition at line 167 of file pid.c.
References dbg_printf(), nav_follow_line(), and PID_FLAG.
Referenced by bullet_point_4(), main(), and main_line_turn().
{
    #ifdef DEBUG
    dbg_printf("PID_FLAG = 1\n\r");
    #endif
    #ifdef POLULU_PID
    nav_follow_line(35);
    #endif
    PID_FLAG = 1;
}
int pid_turn_detect ()
Detecting of LEFT / RIGHT Turn at end of line.
Note
should only run on entry to the PID LOOP
Definition at line 82 of file pid.c.
References sensors, and TURN_FLG.
Referenced by main_line_turn(), and pid_control_loop().
{
    //line_calibrate_read(sensors);
    //pid_read_sensors();
// CASE: LEFT TURN
    if( sensors[0] > 400
    && (sensors[1] > 400
     || sensors[2] > 400
     || sensors[3] > 400)
     && sensors[4] < 300) {
         TURN_FLG = 1;
    }
// CASE: RIGHT TURN
    if( sensors[0] < 300
    && (sensors[1] > 400
     || sensors[2] > 400
     || sensors[3] > 400)
     && sensors[4] > 400) {
         TURN_FLG = 2;
    }
    if ( sensors[1] > 900
      || sensors[2] > 900
      || sensors[3] > 900) {
          return 1;
    }
    return 0;
}
int pid_turn_flg ()
Definition at line 76 of file pid.c.
References TURN_FLG.
Referenced by main_line_follow(), and main_line_turn().
{
    return TURN_FLG;
}
Variable Documentation
short int hit_counter = 0
Definition at line 43 of file pid.c.
Referenced by pid_exit_check().
short int miss_counter = 0
Definition at line 42 of file pid.c.
Referenced by pid_exit_check().
short int PID_FLAG = 0
Definition at line 37 of file pid.c.
Referenced by pid_clear(), pid_control_loop(), pid_run(), and pid_set().
short int PID_RUNNING = 0
Definition at line 38 of file pid.c.
Referenced by pid_check_running(), pid_clear(), pid_control_loop(), and pid_run().
char sensor_pattern = 0
Definition at line 44 of file pid.c.
Referenced by pid_line_detect(), pid_over_line(), and pid_read_sensors().
uint16_t sensors[5]
Definition at line 45 of file pid.c.
short int TURN_FLG = 0
Definition at line 39 of file pid.c.
Referenced by pid_control_loop(), pid_turn_detect(), and pid_turn_flg().