Team Rocket Robotics: pid.h File Reference
pid.h File Reference
Header for Line following code.
Functions
void pid_set ()
Sets Flags which trigger line following.
void pid_clear ()
clear PID flag
int pid_line_detect ()
Line detection for the PID algorithm.
int pid_check_running ()
Check if Line following is in PID LOOP.
int pid_turn_detect ()
Detecting of LEFT / RIGHT Turn at end of line.
void pid_calibrate ()
Calls Auto calibration on Polulu.
void pid_check ()
Checks for lines.
void pid_run ()
Start Line following.
int pid_calc (int prop_current, int *prop_last, int *integral, int *derivative)
Factored out PID calculation function.
void pid_motor_set (int power_diff)
Set Motors move fwd based on PID result.
int pid_turn_flg ()
Detailed Description
Header for Line following code.
Author
Sam Gamble
Definition in file pid.h.
Function Documentation
int pid_calc (int prop_current, int * prop_last, int * integral, int * derivative)
Factored out PID calculation function.
Author
Sam Gamble
Note
based on the PID formula running on polulu, if it gives problems i'll spend some quality time with MATLAB and work out why (if time allows)
Parameters
[in] 'prop_current' expected range (-2000 .. 2000) if not in this range returns 0
[in] 'prop_last','integral' and 'derivative' pointers to integers defined in the calling function. Initial values of the variables should be 0, cal
Warning
the params 'prop_last' 'integral' and 'derivative' are int pointers used to pass by reference. This is required for factoring out the PID algorithum because these values are cumulative (dependent on time).
Definition at line 382 of file pid.c.
References dbg_printf(), Kd, Ki, and Kp.
Referenced by adv_move_pid_polar().
{
    #ifdef DEBUG
    dbg_printf("last_proportional  %d\n\r", *prop_last);
    #endif
    *derivative = prop_current - *prop_last;
    *prop_last = prop_current;
    *integral += prop_current;
    int power_difference = (prop_current/Kp + *integral/Ki + *derivative * 2/Kd);
    #ifdef DEBUG
    dbg_printf("proportional       %d\n\r", prop_current);
    dbg_printf("integral           %d\n\r",*integral);
    dbg_printf("derivative         %d\n\r",*derivative);
    dbg_printf("power_difference   %d\n\r",power_difference);
    #endif
    return power_difference;
}
void pid_calibrate ()
Calls Auto calibration on Polulu.
void pid_check ()
Checks for lines.
Sets flags to enable/disable PID line following based on the underside line sensors
Referenced by RIT_IRQHandler().
int pid_check_running ()
Check if Line following is in PID LOOP.
Note
running -> return 1, exited -> return 0
Definition at line 193 of file pid.c.
References PID_RUNNING.
{
    if(PID_RUNNING)
        return 1;
    else
        return 0;
}
void pid_clear ()
clear PID flag
It can cause PID algorithm to exit.
Definition at line 179 of file pid.c.
References dbg_printf(), nav_stop_follow_line(), PID_FLAG, and PID_RUNNING.
Referenced by pid_exit_check().
{
    #ifdef DEBUG
    dbg_printf("PID_FLAG = 0\n\r");
    #endif
    PID_FLAG = 0;
    PID_RUNNING = 0;
    #ifdef POLULU_PID
    nav_stop_follow_line();
    #endif
}
int pid_line_detect ()
Line detection for the PID algorithm.
Note
should only run on entry to the PID LOOP
Definition at line 128 of file pid.c.
References dbg_printf(), pid_read_sensors(), sensor_pattern, and sensors.
Referenced by nav_search_line().
{
    #ifdef DEBUG
    dbg_printf("-pid line detect-\n\r");
    #endif
    pid_read_sensors(sensor_pattern);
    if(sensor_pattern == 'B') {
        return 0;
    }
    if( sensors[0] == 1000
     || sensors[1] == 1000
     || sensors[2] == 1000
     || sensors[3] == 1000
     || sensors[4] == 1000) {
         return 1;
    }
    return 0;
}
void pid_motor_set (int power_diff)
Set Motors move fwd based on PID result.
Author
Sam Gamble
Warning
Requires #define 'SPEED_OFFSET',currently = 0 (will be set on testing)
Parameters
[in] power difference value (-30 .. +30) if above these values the motor speeds will be capped to (SPEED_OFFSET + SPEED_LIMIT)
Definition at line 403 of file pid.c.
References dbg_printf(), MOTOR_LEFT, MOTOR_RIGHT, motor_set(), SPEED_LIMIT, and SPEED_OFFSET.
Referenced by adv_move_pid_polar().
{
    short int l_speed  = 0;
    short int r_speed = 0;
    if( power_diff > SPEED_LIMIT ) {
        power_diff = SPEED_LIMIT;
    }
    if( power_diff < -SPEED_LIMIT ) {
        power_diff = -SPEED_LIMIT;
    }
    if(power_diff < 0) {
        l_speed  = (short int)(SPEED_OFFSET + SPEED_LIMIT +power_diff);
        r_speed = (short int)(SPEED_OFFSET + SPEED_LIMIT);
    } else {
        l_speed  = (short int)(SPEED_OFFSET + SPEED_LIMIT);
        r_speed = (short int)(SPEED_OFFSET + SPEED_LIMIT -power_diff);
    }
    motor_set(MOTOR_LEFT  ,l_speed);
    motor_set(MOTOR_RIGHT ,r_speed);
    #ifdef DEBUG
    dbg_printf("ADV_PID: L_Motor = %d,  R_Motor = %d" ,l_speed ,r_speed);
    #endif
}
void pid_run ()
Start Line following.
Note, will do NOTHING unless flags are set using either pid_check() or pid_set()
Definition at line 366 of file pid.c.
References dbg_printf(), pid_control_loop(), PID_FLAG, and PID_RUNNING.
Referenced by main_line_follow().
{
    #ifdef DEBUG
    dbg_printf("---pid run---\n\r");
    #endif
    if (PID_RUNNING || !PID_FLAG) return;
        pid_control_loop();
}
void pid_set ()
Sets Flags which trigger line following.
Explicitly sets flags to start / stop pid line following algorithm, should not need to call in most cases, pid_check() will set flags when a line is detected
Definition at line 167 of file pid.c.
References dbg_printf(), nav_follow_line(), and PID_FLAG.
Referenced by bullet_point_4(), main(), and main_line_turn().
{
    #ifdef DEBUG
    dbg_printf("PID_FLAG = 1\n\r");
    #endif
    #ifdef POLULU_PID
    nav_follow_line(35);
    #endif
    PID_FLAG = 1;
}
int pid_turn_detect ()
Detecting of LEFT / RIGHT Turn at end of line.
Note
should only run on entry to the PID LOOP
Definition at line 82 of file pid.c.
References sensors, and TURN_FLG.
Referenced by main_line_turn(), and pid_control_loop().
{
    //line_calibrate_read(sensors);
    //pid_read_sensors();
// CASE: LEFT TURN
    if( sensors[0] > 400
    && (sensors[1] > 400
     || sensors[2] > 400
     || sensors[3] > 400)
     && sensors[4] < 300) {
         TURN_FLG = 1;
    }
// CASE: RIGHT TURN
    if( sensors[0] < 300
    && (sensors[1] > 400
     || sensors[2] > 400
     || sensors[3] > 400)
     && sensors[4] > 400) {
         TURN_FLG = 2;
    }
    if ( sensors[1] > 900
      || sensors[2] > 900
      || sensors[3] > 900) {
          return 1;
    }
    return 0;
}
int pid_turn_flg ()
Definition at line 76 of file pid.c.
References TURN_FLG.
Referenced by main_line_follow(), and main_line_turn().
{
    return TURN_FLG;
}