Team Rocket Robotics: utilities.h File Reference
utilities.h File Reference
Polulu control utilities (header)
Functions
int request_sig (char *read_sig)
Request the version of the slave code that is running.
int read_trimpot ()
Request the trimpot value.
int read_battery ()
Request battery voltage.
void play_music (char *score)
Play music on Pololu.
Detailed Description
Polulu control utilities (header)
This module handles miscellaneous commands to AVR processor on the Polulu
Author
Sam Gamble (added in the function defs)
Fufu Fang (tidying up)
Definition in file utilities.h.
Function Documentation
void play_music (char * score)
Play music on Pololu.
For how to compose music score, please look at: http://www.pololu.com/docs/0J18/3
Parameters
score pointer to your music score
Definition at line 49 of file utilities.c.
References dbg_printf(), and uart_send_blk().
Referenced by main_line_turn().
{
    uint8_t score_length = strlen(score);
    //command (1 byte), length of music string(1 bytes), music(100 bytes MAX)
    uint8_t send_score[score_length + 2];
    int i;
    send_score[0] = 0xB3;
    send_score[1] = score_length;
    for (i = 0; i < score_length + 2; i++) {
        send_score[i + 2] = score[i];
    }
    /* Debugging info */
    dbg_printf("Music Output Stream: %X %d ", send_score[0],
               send_score[1]);
    for (i = 2; i < score_length + 2; i++) {
        dbg_printf("%c", send_score[i]);
    }
    dbg_printf("    Send Length = %d", score_length + 2);
    dbg_printf("\n\r");
    uart_send_blk(send_score, score_length + 2);
}
int read_battery ()
Request battery voltage.
Returns
battery voltage in milivolt
Definition at line 39 of file utilities.c.
References BATTERY, dbg_printf(), uart_recv_blk(), and uart_send_byte().
{
    uint16_t reading;
    uint8_t *data = (uint8_t *) & reading;
    uart_send_byte(BATTERY);
    uart_recv_blk(data, 2);
    dbg_printf("Battery voltage: %d mV");
    return reading;
}
int read_trimpot ()
Request the trimpot value.
the trimpot is used for some kind of calibration.
Returns
current trimpot settings, between 0 to 1023.
Definition at line 29 of file utilities.c.
References dbg_printf(), TRIMPOT, uart_recv_blk(), and uart_send_byte().
{
    uint16_t reading;
    uint8_t *data = (uint8_t *) & reading;
    uart_send_byte(TRIMPOT);
    uart_recv_blk(data, 2);
    dbg_printf("Trimpot reading: %d\r\n");
    return reading;
}
int request_sig (char * read_sig)
Request the version of the slave code that is running.
Note
This function also shuts down the motors and disables PID, so it is useful as an initial command.
Returns
version number of the slave code
Definition at line 22 of file utilities.c.
References SIGNATURE, uart_recv_blk(), and uart_send_byte().
{
    uint8_t *data = (uint8_t *) read_sig;
    uart_send_byte(SIGNATURE);
    return uart_recv_blk(data, 6);
}