Team Rocket Robotics: wall_follow.c File Reference
wall_follow.c File Reference
#include "wall_follow.h"
#include "ir.h"
#include "motor.h"
#include "delay.h"
#include "gpio.h"
Macros
#define TOLERANCE 10
#define DELAY 200
#define OBSTACLE 0.3
Functions
static void update_sensors ()
void nav_follow_wall (nav_Wall wall)
Set the robot to follow a wall.
void nav_stop_follow_wall ()
Stop the wall following algorithm.
void follow_wall_start ()
void follow_wall_stop ()
External start and stop commands for wall follow.
Variables
short int WALL_FOLLOW_FLAG = 1
int wallFollowing = 0
ir_Sensor fSensor
ir_Sensor bSensor
int fReading
int bReading
int prevFReading
int prevBReading
Detailed Description
Author
Oliver Loftus
Contains wall following algorithms
Definition in file wall_follow.c.
Macro Definition Documentation
#define DELAY 200
Definition at line 17 of file wall_follow.c.
Referenced by nav_follow_wall().
#define OBSTACLE 0.3
Definition at line 18 of file wall_follow.c.
#define TOLERANCE 10
Definition at line 16 of file wall_follow.c.
Referenced by nav_follow_wall().
Function Documentation
void follow_wall_start ()
Definition at line 115 of file wall_follow.c.
References WALL_FOLLOW_FLAG.
{
    WALL_FOLLOW_FLAG = 1;
}
void follow_wall_stop ()
External start and stop commands for wall follow.
Definition at line 120 of file wall_follow.c.
References nav_stop_follow_wall(), and WALL_FOLLOW_FLAG.
{
    nav_stop_follow_wall();
    WALL_FOLLOW_FLAG = 0;
}
void nav_follow_wall (nav_Wall wall)
Set the robot to follow a wall.
***** Detect a wall ahead *****/
Definition at line 37 of file wall_follow.c.
References BACK_LEFT, BACK_RIGHT, bReading, bSensor, DELAY, delay_start(), fReading, FRONT_LEFT, FRONT_RIGHT, fSensor, gpio_collision_read(), MOTOR_LEFT, motor_read(), MOTOR_RIGHT, motor_set(), motors_move(), motors_stop(), TOLERANCE, update_sensors(), WALL_DISTANCE, WALL_FOLLOW_FLAG, WALL_LEFT, WALL_RIGHT, and wallFollowing.
Referenced by bullet_point_1_and_2().
{
    if(!WALL_FOLLOW_FLAG)
    {
        return;
    }
    fSensor = wall == WALL_RIGHT ? FRONT_RIGHT : FRONT_LEFT;
    bSensor = wall == WALL_RIGHT ? BACK_RIGHT : BACK_LEFT;
    int speed = motor_read(MOTOR_LEFT);
    int pTurnSpeed = speed*0.6;
    int dTurnSpeed = speed*0.3;
    int delay = (DELAY*10)/speed;
    motors_move(speed); // Start the robot running straight
    wallFollowing = 1;
    while (wallFollowing)
    {
        /***** Staying parallel to the wall/correcting small errors *****/
        update_sensors();
        if (fReading - bReading > TOLERANCE || bReading - fReading > TOLERANCE) // fSensorReading != bSensorReading
        {
            if ((wall == WALL_RIGHT && fReading - bReading > TOLERANCE) || // fReading > bReading
                (wall == WALL_LEFT && bReading - fReading > TOLERANCE)) // fReading < bReading
            {
                motor_set(MOTOR_RIGHT, pTurnSpeed);
            }
            else if ((wall == WALL_RIGHT && bReading - fReading > TOLERANCE) || // fReading < bReading
                     (wall == WALL_LEFT && fReading - bReading > TOLERANCE)) // fReading > bReading
            {
                motor_set(MOTOR_LEFT, pTurnSpeed);
            }
            do { update_sensors(); }
            while (fReading - bReading > TOLERANCE || bReading - fReading > TOLERANCE); // fSensorReading != bSensorReading
            motors_move(speed);
        }
        /***** Navigating to the correct distance from the wall *****/
        update_sensors();
        if ((wall == WALL_RIGHT && WALL_DISTANCE - fReading > TOLERANCE) || // Too far
            (wall == WALL_LEFT && fReading - WALL_DISTANCE > TOLERANCE))
        {
            if (wall == WALL_LEFT) dTurnSpeed = 0; // Fix for problem specific to robot 6
            motor_set(MOTOR_LEFT, dTurnSpeed);
            delay_start(delay);
            motor_set(MOTOR_LEFT, speed); // Go in a straight line
        }
        else if ((wall == WALL_RIGHT && fReading - WALL_DISTANCE > TOLERANCE) || // Too close
                 (wall == WALL_LEFT && WALL_DISTANCE - fReading > TOLERANCE))
        {
            motor_set(MOTOR_RIGHT, dTurnSpeed);
            delay_start(delay);
            motor_set(MOTOR_RIGHT, speed);
        }
        delay_start(delay); // Wait for the robot to go a little before rechecking
        if (gpio_collision_read())
        {
            motors_stop();
            while (gpio_collision_read()) delay_start(10);
            motors_move(speed);
        }
    }
}
void nav_stop_follow_wall ()
Stop the wall following algorithm.
Definition at line 109 of file wall_follow.c.
References wallFollowing.
Referenced by follow_wall_stop().
{
    wallFollowing = 0;
}
static void update_sensors () static
Definition at line 31 of file wall_follow.c.
References bReading, bSensor, fReading, fSensor, and ir_read().
Referenced by nav_follow_wall().
{
    fReading = ir_read(fSensor);
    bReading = ir_read(bSensor);
}
Variable Documentation
int bReading
Definition at line 27 of file wall_follow.c.
Referenced by nav_follow_wall(), and update_sensors().
ir_Sensor bSensor
Definition at line 26 of file wall_follow.c.
Referenced by nav_follow_wall(), and update_sensors().
int fReading
Definition at line 27 of file wall_follow.c.
Referenced by nav_follow_wall(), and update_sensors().
ir_Sensor fSensor
Definition at line 26 of file wall_follow.c.
Referenced by nav_follow_wall(), and update_sensors().
int prevBReading
Definition at line 28 of file wall_follow.c.
int prevFReading
Definition at line 28 of file wall_follow.c.
short int WALL_FOLLOW_FLAG = 1
Definition at line 20 of file wall_follow.c.
Referenced by follow_wall_start(), follow_wall_stop(), and nav_follow_wall().
int wallFollowing = 0
Definition at line 24 of file wall_follow.c.
Referenced by nav_follow_wall(), and nav_stop_follow_wall().